### ISSUE TITLE
Create rebass-base package?

### ISSUE THREAD

**Issue by TimMikeladze** [jxnblk/rebass#100]
I think it would be useful to have `src/Base.js` and its dependancies be moved into a `rebass-base` package so you could build standalone rebass components without pulling in the entire library.

**Comment by jxnblk** [comment]
How would this be different than `import Base from 'rebass/dist/Base'`?

**Comment by jxnblk** [comment]
FWIW I've created a separate higher order component that has a lot of the same functionality as the Base component here: https://github.com/jxnblk/robox
