### ISSUE TITLE
input onChange/onBlur error

### ISSUE THREAD

**Issue by ryuken** [jxnblk/rebass#102]
I updated to 0.3.0 and get the following error when using onChange or onBlur with Input.
As soon as I type something in the Input I get this error:

warning.js?8a56:44 Warning: Base is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by ryuken** [comment]
My bad when I use defaultValue I get no error

**Comment by ryuken** [comment]
Issue still exists with controlled inputs

**Comment by ryuken** [comment]
The same applies to other input fields like Select, Radio, etc.

**Comment by steida** [comment]
It works well when onChange prop is specified which is the must anyway. The only one fixable problem in this library would be an addition warning, since "changing an uncontrolled input of type text to be controlled" is a bit cryptic.
