### ISSUE TITLE
Can't change InlineForm button type

### ISSUE THREAD

**Issue by sniepoort** [jxnblk/rebass#111]
Since this is a react library (where an SPA is likely), it seems a bit silly that the button in the inline form has type="submit", causing a page reload. How can I get around this?

**Comment by jxnblk** [comment]
The button has a type attribute for semantic correctness, accessibility, and server-rendered HTML forms (e.g. Progressive enhancement), with js, use `e.preventDefault()` in your submit handler. This is fairly common practice even outside of React, but please let me know if you're still having issues
