### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by steida** [jxnblk/rebass#114]
The same approach I suggested for react-intl https://github.com/yahoo/react-intl/issues/600

**Comment by jxnblk** [comment]
I'm curious what this would entail for rebass specifically. I'd imagine most of that logic could be contained within the Base component.

**Comment by steida** [comment]
Can't be, because Base can not require / import both from React and React Native to be usable universally. Conditional require is no-go since dead code removal would not work in Webpack 2. I think we should have two different higher order components for that.

**Comment by steida** [comment]
> I'm curious what this would entail for rebass specifically.

span can not be rendered in React Native. We need Text. Otherwise almost everything should be the same, except platform specific stuff of course.

**Comment by steida** [comment]
The world needs universal UI with the common dictionary. Your library is the unicorn because it's only presentional and very thoughtful.

**Comment by thomaswright** [comment]
Hi @jxnblk , I like your work and wanted to use something like rebass for native, so I built react native component library off a modified core of rebass. @steida, it definitely isn't striving toward universality, but if you're looking for a similar solution maybe check it out. :)

https://github.com/thomaswright/bayst

**Comment by jxnblk** [comment]
I'm hoping with the new setup in v1 that exporting a react native version using react-primitives is something I can get to in the near future, but for now I'm considering this library web-centric as I never do any work on native applications

**Comment by MiguelMadero** [comment]
Hi @jxnblk we're interested in having a universal UI library, if this is something that aligns with the goals of this project we could help out with the work required to take it in that direction

**Comment by rsaccon** [comment]
I am also interested in this !!!

**Comment by jxnblk** [comment]
I'm open to considering this. Still not sure if it's something that should be part of this repo, or a separate one, but would be open to a PR for discussion. I think the first thing I'd try is using `styled-components/primitives` and a mapping between a component's `type` and a relevant `react-primitive`

**Comment by rsaccon** [comment]
I found the following article relevant to this topic: https://medium.com/styled-components/announcing-primitives-support-for-truly-universal-component-systems-5772c7d14bc7. Should the issue be reopened to keep the discussion more visibly alive ?

**Comment by MiguelMadero** [comment]
Thanks, @jxnblk that's exactly what we were thinking and @rsaccon we were basing a lot of the ideas in that article. 

We gave it a quick go and it still feels like styled-components/primitives are not ready, we had a few issues and found it a bit too limiting. This isn't an immediate need for us so we won't be exploring it further for a least a few months, but we'll come back to this once we start working on our react-native integration to see if things have changed. 

Thanks

**Comment by MiguelMadero** [comment]
@airato maybe open sourcing zbase could fill in this gap...
