### ISSUE TITLE
Question about ...props

### ISSUE THREAD

**Issue by steida** [jxnblk/rebass#115]
For example here:

`const Close = ({ ...props }, { rebass }) => {`

I don't see why props must be shallowly cloned?
What's wrong with:

`const Close = (props, { rebass }) => {`?

**Comment by jxnblk** [comment]
I believe this stemmed from a desire for code consistency, but for components that don't support custom props, it should probably be removed.

**Comment by steida** [comment]
I see. Thank you for the answer. It could be confusing for the people.
