### ISSUE TITLE
Questions about lineHeight

### ISSUE THREAD

**Issue by steida** [jxnblk/rebass#116]
lineHeight is recommended to be set in CSS on the body only.

1) Does it mean all elements will inherit it?
2) Does it mean we should use the same lineHeight across whole design?
3) Is that reason why lineHeight is not part of the config nor props?

**Comment by jxnblk** [comment]
1. Yes
2. Sort of; depends on your design
3. You can set specific line heights per component, for example with the Header

**Comment by steida** [comment]
Thank you!
