### ISSUE TITLE
Where do certain default colors get used?

### ISSUE THREAD

**Issue by wlingke** [jxnblk/rebass#117]
In your example config you had a section: 

```
const colors = {
  ...baseColors,
  primary: baseColors.blue,
  secondary: baseColors.midgray,
  default: baseColors.black,
  info: baseColors.blue,
  success: baseColors.green,
  warning: baseColors.orange,
  error: baseColors.red
}
```

Where do these primary, secondary, ... etc, getting used? Can we customize components and change a text color to "primary" without having to import this config (and passing it through style)?

**Comment by lachlanjc** [comment]
Yep, you sure can!

```js
<Text theme='primary'>Blue text</Text>
```
