### ISSUE TITLE
PageHeader should allow components for description and heading

### ISSUE THREAD

**Issue by steida** [jxnblk/rebass#127]
Your library is the super awesome masterpiece. I am in process of implementing it into https://github.com/este/este Sorry for disturbing you with issues, maybe I can help you.

**Comment by jxnblk** [comment]
Can you clarify? The

**Comment by steida** [comment]
The ability to pass React component instead of the string only. https://github.com/jxnblk/rebass/blob/master/src/PageHeader.js#L50
