### ISSUE TITLE
Suggestions from implementing Rebase in Este.js

### ISSUE THREAD

**Issue by steida** [jxnblk/rebass#128]
At first, Rebass is pure beauty. Thank you!

Implementing it into https://este.firebaseapp.com I encountered some small issues here and there, but overall it was quite a smooth process.

But one thing was super tricky: https://github.com/este/este/blob/cfb03d6bb5dabaddbc008e883aff685d8895d79d/src/browser/app/App.js#L29

Rebass needs such provider.

**Comment by jxnblk** [comment]
Thanks!

But I think this issue is too vague. If you have a specific issue or suggestion please open a new issue

**Comment by steida** [comment]
Sure. Sorry for misusing rebass issues for thoughts flashes.
