### ISSUE TITLE
Howto: Specify Footer without top border

### ISSUE THREAD

**Issue by TheoMer** [jxnblk/rebass#129]
How do I specify a footer without the top border,or any other rebase component, for that matter, which has a top border?

**Comment by lehmuskoski** [comment]
<Footer style={{borderTop: 'none'}}>
</Footer>

**Comment by TheoMer** [comment]
Many thanks.

**Comment by steida** [comment]
TheoMer, can you please at least close the issue? Also, can you read https://github.com/este/este/blob/master/ISSUE_TEMPLATE? Do you know what does it mean? So please respect us and ask stackoverflow next time, thank you.

**Comment by steida** [comment]
TheoMer, can you close the issue you opened at least?
