### ISSUE TITLE
default color in rebass theme

### ISSUE THREAD

**Issue by martynasj** [jxnblk/rebass#136]
Hi. Waht is the use for default color in rebass components? We're trying to utilise the color scheme, and we were to use `colors.default` as our main color for borders and outlines. Although it makes things a bit more complicated as it is a reserved word, so it can't be used in destructuring pattern. Small thing but still

```
const { default: defaultColor, primary, mutedText } = this.context.rebass.colors;
```

**Comment by jxnblk** [comment]
The color palette in v1 no longer has a `default` key, so hopefully this isn't an issue anymore
