### ISSUE TITLE
Fixed aspect ratio component

### ISSUE THREAD

**Issue by RileyTomasek** [jxnblk/rebass#138]
It would be really nice to have a component that allowed a specific aspect ratio to be forced, for any supplied image. This is useful for making grids line up nicely when images are user inputed. It also helps with keeping card components the same size.

**Comment by Ghust1995** [comment]
Is there any alternative solution to keep card components the same size?

**Comment by jxnblk** [comment]
Thanks for the suggestion! v1 now has a BackgroundImage component that supports a `ratio` prop
