### ISSUE TITLE
Consider airbnb instead of "standard"

### ISSUE THREAD

**Issue by steida** [jxnblk/rebass#139]
The airbnb is the standard: 40700 > 7300 github stars.
But that's not the point. The point is airbnb is much stricter and wider. 
Check https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1
It uses eslint, eslint-plugin-import, eslint-plugin-react, and eslint-plugin-jsx-a11y

What do you think?

**Comment by Kikobeats** [comment]
but why?

**Comment by bentatum** [comment]
[airbnb](https://github.com/airbnb/javascript) is on version 11 and counting. it's tough to keep up with.

**Comment by steida** [comment]
It is, but it ensures the most precise code style.

**Comment by j0hnsmith** [comment]
+1 for airbnb, it's a really nice set of rules, anyone who hasn't tried it should.

**Comment by dcousens** [comment]
`standard` is increasingly becoming stricter... so I don't think that is a fair point.
