### ISSUE TITLE
propTypes

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/rebass#14]
Just seems like the right thing to do: https://facebook.github.io/react/docs/reusable-components.html#prop-validation

**Comment by chrislloyd** [comment]
Hey I've got a PR coming to add proper `propTypes` to most components. Feel free to move fast on this one but if you can wait to Monday it's less work you need to do.

**Comment by jxnblk** [comment]
Oh yeah. I just added this because you mentioned it :)
