### ISSUE TITLE
Tooltip Placement Options

### ISSUE THREAD

**Issue by olsonek** [jxnblk/rebass#143]
Short of overriding styles, I don't see an easy way to change which side tooltips show from.

React-Bootstrap accepts the prop "placement" that lets you specify "left", "right", "top", or "bottom" to determine the side in which the tooltip will appear.

Would this be a welcome feature or does this go against a style guideline/design decision?

**Comment by theopak** [comment]
![6h1ejjqlj2 1](https://cloud.githubusercontent.com/assets/693878/21703612/83b65308-d381-11e6-80b9-bba1e40e8dc1.gif)


Hey @olsonek I needed this too so I took a shot at it. Does PR #205 do what you were thinking of?

**Comment by olsonek** [comment]
That looks exactly like what I was looking for! Thanks :)

**Comment by theopak** [comment]
@olsonek great! If you have some extra time then a quick comment/code review of my PR might help make it easier for @jxnblk to figure out whether to merge it.
