### ISSUE TITLE
HeadingLink to support routers components 

### ISSUE THREAD

**Issue by mrsufgi** [jxnblk/rebass#146]
Hey, 

I've been using LinkBlock with {Link} component from react-router, could you consider rebuilding HeadingLink to take an object (such as Link) as it linking object (instead of just take 'href' prop) 

Maybe I can use a <LinkBlock> with a <Heading> tag inside ? Currently, I'm wrapping Heading with Link.

Thanks :)

**Comment by keithn** [comment]
you might be interested in #36
