### ISSUE TITLE
Tabs component

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/rebass#149]

**Comment by souporserious** [comment]
I'm still actively working on this. But would you be interested in using [React ARIA](https://github.com/souporserious/react-aria) for [Tabs](https://github.com/souporserious/react-aria/tree/master/src/Tabs) and other things like [Select](https://github.com/souporserious/react-aria/tree/master/src/Select) menus in Rebass? I'm open to any suggestions to help get it integrated in here if you are interested. I've been meaning to use `lerna` so modules can be used independently.
