### ISSUE TITLE
What is the nicest way to create a page that starts after clearing the top fixed header?

### ISSUE THREAD

**Issue by keithn** [jxnblk/rebass#157]
For example, in the demo

![image](https://cloud.githubusercontent.com/assets/86080/19026368/904bbea4-8981-11e6-95f8-6a5a32ea6bf6.png)

How what's the cleanest way to start putting things where the yellow scribble is :)

**Comment by jxnblk** [comment]
If you're using fixed positioning, you'll want to add margin or padding top to compensate for the height of the element, but this is just general CSS and not related to Rebass. Also be aware of the fixed element's height changing due to child components wrapping
