### ISSUE TITLE
Rebass with Radium

### ISSUE THREAD

**Issue by wlingke** [jxnblk/rebass#159]
In an effort to be truly CSS-independent, I'm trying to get Radium to work with Rebass - specifically because of pseudo classes like `:hover` and media queries. Unfortunately, I have not been able to get it to work because both Radium and Rebass use the `style` prop.

Any suggestions here?

**Comment by mrsufgi** [comment]
radium or any JSS framework/library would be superawesome

**Comment by dmackerman** [comment]
Same with Aphrodite as well.

**Comment by mrsufgi** [comment]
Aphroditing the rebass, so awesome!

**Comment by dmackerman** [comment]
What appears to be a simple solution (at least for the `className` usecase) is to just append the className prop that gets passed in to every component.  

Instead of `className='Breadcrumbs'`, maybe just 

```
className={`Breadcrumbs ${props.className}`}
```

**Comment by jxnblk** [comment]
Glamor and Aphrodite are probably front runners for being used in the library itself. As for the className prop, v0.4 supports passing custom classnames, so they should work there

**Comment by dmackerman** [comment]
Sounds good @jxnblk. My vote is for Aphrodite. 👍 

When do you expect 0.4 to be out?

**Comment by steida** [comment]
@jxnblk I think https://github.com/rofrischmann/fela is probably the winner. Check it.

**Comment by maotora** [comment]
@steida Hello, I love the suggestion you gave and read the fela documentation.

I wonder how do you use fela with rebass. Can you maybe offer an example please?

Thanks!

**Comment by peterpme** [comment]
:wave: I'd be interested in helping move this over to Glamor.

**Comment by jxnblk** [comment]
And... I ended up using styled-components. Mostly for the community, active development, and extensibility. Thanks all for the discussion! 😎
