### ISSUE TITLE
Custom colors used in style prop don't work

### ISSUE THREAD

**Issue by pcgilday** [jxnblk/rebass#163]
The custom colors set in context don't work when applied as a value in the `style` prop. There are tests checking this in most components ([example](https://github.com/jxnblk/rebass/blob/master/test/Donut.spec.js#L117)); however, it does not seem to render the proper color. This seems to be because `Base` uses the `color-style` util to get the value for a custom color before rendering ([here](https://github.com/jxnblk/rebass/blob/master/src/Base.js#L146)); however, colors set in `style` prop don't go through this transform. Custom colors need to be set using the `color` property to be transformed. 

Using the `color` property for custom colors works and is probably a fine solution, but since the tests/docs seem to indicate the `style` prop should work with custom colors, this should either be fixed, or updated to reflect that the `color` prop should be used when setting custom colors. 

I am more than happy to submit a PR for this, I would just need to know which direction is preferable. I think it is perfectly reasonable to say custom colors need to be set through the `color` prop for now and update docs/test to account for that; however, if you feel strongly about adding support for custom colors in the `style` prop let me know and we can determine the best approach to handle this. 

This is a great library, thanks for all your hard work!

**Comment by jxnblk** [comment]
I think this shouldn't be an issue in v1, but feel free to reopen if needed
