### ISSUE TITLE
Rating component stars not aligning properly in Firefox

### ISSUE THREAD

**Issue by blakek** [jxnblk/rebass#172]
I've tested several versions of FF (v. 49 to whatever the latest developer edition is), and the stars for the rating component aren't aligning properly.

**Screenshot from demo page:**

![screen shot 2016-11-13 at 9 06 04 pm](https://cloud.githubusercontent.com/assets/4932702/20252113/02e5472c-a9e5-11e6-936d-0d3722374ac5.png)

Sorry if this has been reported before or is a known issue; I tried looking before opening an issue.

Thanks for the awesome library!

**Comment by jxnblk** [comment]
Sorry, not sure what the issue is here, but I've currently removed the Rating component from v1. Feel free to reopen this if needed
