### ISSUE TITLE
`style` prop only affects wrapper Input component

### ISSUE THREAD

**Issue by luisrudge** [jxnblk/rebass#177]
`<Input style={{outline: '0'}} />`
the `outline: 0` style is being applied to the wrapper, not the input itself, so it has no effect at all

![image](https://cloud.githubusercontent.com/assets/941075/20454594/751052a6-ae2c-11e6-9568-69139cc888ab.png)

**Comment by jxnblk** [comment]
Thanks! This shouldn't be an issue anymore in v1
