### ISSUE TITLE
different style for a disabled button

### ISSUE THREAD

**Issue by luisrudge** [jxnblk/rebass#179]
currently, when you disable a button, it only disables clicking on it. it'd be pretty cool to also change the styling based on the disabled attribute

**Comment by jxnblk** [comment]
This is possible with v1 since it uses styled-components (and CSS)

**Comment by carlorizzante** [comment]
Yes, but how would you do it? There is any example?
Thanks in advance.

**Comment by sb8244** [comment]
@carlorizzante for now I'm doing this:

```
export const Button = styled(Rebass.Button)`
  cursor: pointer;

  &:disabled {
    cursor: not-allowed;
    opacity: 0.4;
  }
`
```

Opacity is not the best way to style a disabled button, but it works for now and I can swap it out if I want to. Big benefit of the opacity approach is that it is color-independent.
