### ISSUE TITLE
Problems with universal rendering

### ISSUE THREAD

**Issue by olifante** [jxnblk/rebass#182]
I've created a version of the [rebass demo](http://jxnblk.com/rebass/demo/) with universal rendering, using [next.js](https://github.com/zeit/next.js). The demo is live here: https://next-rebass-example.now.sh/demo

It looks mostly identical to the original (I copied the code and components from your demo), except for one big difference: All "Box" elements seem to take up 100% width, so that instead of getting three cards on a row, each card gets rendered in its own row.

I've looked at the CSS to see what the difference is, but cannot identify the source of the problem. Can you tell me what I'm doing wrong?

**Comment by jxnblk** [comment]
I'm not sure what the issue would be here – hopefully you figured it out or v1 fixes this issue. Feel free to reopen this if needed
