### ISSUE TITLE
Customizing Dropdown Menu Style

### ISSUE THREAD

**Issue by sherryxiao1988** [jxnblk/rebass#183]
I want to customize the border style for the dropdown menu. However, passing inline style to DropdownMenu seems created borders for both Base and Menu.

As according to the code:
<img width="329" alt="image" src="https://cloud.githubusercontent.com/assets/1202426/20753506/a8f13b12-b741-11e6-916f-dffe137d4834.png">

What I have now:
<img width="462" alt="image" src="https://cloud.githubusercontent.com/assets/1202426/20753572/f7e0bf9a-b741-11e6-8bcd-36ef0696ee0f.png">

I want to change the dropdown menu border to be the same color as the label border and also make dropdown menu's border-top width equals to 0

Any workaround to customize the dropdown menu border styles?

**Comment by jxnblk** [comment]
This should be possible in v1 now, though the component library has changed quite a bit
