### ISSUE TITLE
Can't get components to inherit styles 🎨

### ISSUE THREAD

**Issue by alistaircolling** [jxnblk/rebass#232]
Hiya, first off, what a great library!

I want to set the styles for my application so that they are inherited throughout e.g. `fontFamily` is set in 1 place and all buttons, labels, textfields have the same font. I can't get the font or backgroundColor to be inherited. I think I'm missing something obvious.

Can anyone help? :)

Thanks!

Inside `App.js`:
```
  getChildContext () {
    return {
      rebass: {
        fontFamily: 'Georgia',
        fontSizes: [ 64, 48, 24, 18, 16, 14, 12],
        backgroundColor: 'red',
        Button: {
          backgroundColor:'inherit',
          color:'inherit'
        },
        Heading: {
          color: 'inherit',
          fontFamily: 'inherit'
        }
      }
    };
  }
.....
App.childContextTypes = {
  rebass: React.PropTypes.object
};

```

**Comment by jxnblk** [comment]
I think you'd want to set font family on the body. V1 now has a way to add a font family with the Provider component
