### ISSUE TITLE
Toolbar background is invalid

### ISSUE THREAD

**Issue by myaskevich** [jxnblk/rebass#238]
Hi,

I'm super excited you're giving rebass another spin!

I'm trying to use it and understand it may be unstable.

<Toolbar /> component doesn't have any background.

<img width="433" alt="screen shot 2017-07-05 at 6 40 22 pm" src="https://user-images.githubusercontent.com/958221/27872486-9d336956-61b1-11e7-8a12-a64cee720b8c.png">

Also in inspector I see the color is set, but it's invalid:

<img width="323" alt="screen shot 2017-07-05 at 6 42 09 pm" src="https://user-images.githubusercontent.com/958221/27872519-b9ea489e-61b1-11e7-8374-1c4c6148a1ac.png">

I'm using latest Canary browser.

**Comment by jxnblk** [comment]
Hey sorry, I missed a typo when changing how the color palette worked, should be fixed in `1.0.0-1`
