### ISSUE TITLE
Are you opened to pull request?

### ISSUE THREAD

**Issue by borisrorsvort** [jxnblk/rebass#24]
if yes, there is a bit of work to make it work since you make internal ref to github repos we dont have access to. Also half of npm deps are out-of date. Basically its unbuildable in the current state.
Do you think you can make it ready for PRs ?
I'd love to propose you some new components :p

**Comment by jxnblk** [comment]
This repo should not be referencing any private repos or modules, and I can't reproduce any build issues. If you have a specific example of something not working, please open a new issue and I'll take a look.
