### ISSUE TITLE
Can you please link to similar projects?

### ISSUE THREAD

**Issue by javajosh** [jxnblk/rebass#241]
For those of us new to the React space, and shopping for component libraries, especially in a functional style, it would be useful to get some links to what *you* consider "close" in style, or "on the right path" but not quite there, which is why you made *rebass*. I'd also like to hear about the trade-offs you made designing this library. Why did you alias well-known style attributes, for example? Are you optimizing for JSX read ability? Compactness? Simplicity at runtime? And so on.

Optional, but appreciated.

**Comment by jxnblk** [comment]
There is a *Related* section in the docs https://github.com/jxnblk/rebass#related

I don't know of any other component libraries out there like Rebass (stateless, customizable, design-system-based, etc.), and that's part of the reason I started this. This post gets at a little more of the philosophy behind Rebass http://jxnblk.com/writing/posts/patterns-for-style-composition-in-react/

As for *trade-offs*, personally I don't think that I've made any in this library. There might be some performance issues which I hope will generally improve over time, but I think it's good enough for a production application.

Feel free to continue the conversation here or reopen this issue if you have any other specific questions
