### ISSUE TITLE
mad jitter on macOS latest chrome

### ISSUE THREAD

**Issue by rileytg** [jxnblk/rebass#242]
wasn't even gonna open this issue until i checked it out again on ios. totally smooth on ios. on my top spec new imac with latest chrome, mucho jitters on scroll and a lil bit on interaction with components. 

happy to provide more debug info, just lemme know what you want/need

**Comment by jxnblk** [comment]
If you're referring to the animation in the docs site, the CSS is spec-compliant as far as I can tell. I believe what you're seeing is a bug in Chrome, it you'd like to open an issue there. Feel free to reopen if I've misunderstood you.

**Comment by rileytg** [comment]
jitter gone with an update :)
