### ISSUE TITLE
Possible issue with components demonstration?

### ISSUE THREAD

**Issue by reflog** [jxnblk/rebass#244]
Hi!
Lovely project, very nicely done!
Wanted to point out a possible issue with the components demo on the website:
![image](https://user-images.githubusercontent.com/109876/27918648-4795f334-6278-11e7-85f2-bc7fc33fde3e.png)

1. bottom right - is displayed in top right
2. fixed - empty, no message

**Comment by jxnblk** [comment]
I need to clean up the demo container but 1 is in the bottom right of its container and 2 is in the bottom right of the viewport (because it's fixed positioning – I thought it was funny but who knows)
