### ISSUE TITLE
Replacement for Space

### ISSUE THREAD

**Issue by TAQ2** [jxnblk/rebass#246]
Hello, thanks for reading.

In the previous version of rebass there was a Space component. I was wondering if there is a substitute method in rebass@next

Thanks :)

**Comment by jxnblk** [comment]
You *should* be able to use the `<Box />` component to similar effect.

```jsx
// Either
<Box mr={2} />
// or something like
<Box w={16} />
```

**Comment by TAQ2** [comment]
Thanks! I'll try it out
