### ISSUE TITLE
Issues during build

### ISSUE THREAD

**Issue by borisrorsvort** [jxnblk/rebass#25]
First issue is that in package.json you reference 
```
"basscss.github.io": "github:basscss/basscss.github.io"
```

but since its ssh version only you get access. So npm install will only work if changed to:

```
"basscss.github.io": "https://github.com/basscss/basscss.git"
```

then npm start fails on some docs.css, here is the paste bin http://pastebin.com/DQhkDdDp

**Comment by chrislloyd** [comment]
Confirmed. Looking into a solution. BTW, `docs.css` is failing because it can't load the `basscss.github.io` dependency.

**Comment by borisrorsvort** [comment]
Its failing even if you make the suggested change, that the weird thing

**Comment by borisrorsvort** [comment]
@jxnblk any news for this one too?

**Comment by jxnblk** [comment]
Looks like the webpack config wasn't properly getting `docs.css`. It looks like it *should* work, but just forced the loader in the import statement for now.

**Comment by borisrorsvort** [comment]
<img width="559" alt="screenshot 2015-08-05 21 48 24" src="https://cloud.githubusercontent.com/assets/39081/9096158/ca047f60-3bbb-11e5-9c8a-04b4edff1194.png">

**Comment by jxnblk** [comment]
I really have no idea how to reproduce this. If you wanna help debug it, I'd suggest trying to import a different CSS file. If that works, then layer in the imports to isolate what's happening.

**Comment by chrislloyd** [comment]
The problem lies with `basscss.github.io` and `rebass` both depending on each other, creating a circular reference. Unfortunately NPM doesn't give very much helpful output to debug the where the conflict is coming from. The `docs.css` being missing is the result of a partial `npm install`, not a loader issue.

Try a fresh clone of the repo and `npm install`'in to debug.

**Comment by jxnblk** [comment]
Maybe I'm missing something, but where is `basscss.github.io` depending on `rebass`? https://github.com/basscss/basscss.github.io/blob/master/package.json

**Comment by borisrorsvort** [comment]
In showcase there is a circular reference:
https://github.com/basscss/showcase/blob/gh-pages/package.json
https://github.com/basscss/basscss.github.io/blob/master/package.json
