### ISSUE TITLE
Border component doesn't have access to colour palette

### ISSUE THREAD

**Issue by darArch** [jxnblk/rebass#252]
I'm having trouble styling a `<Border>...</Border>` component. I've set up a provider with a theme including some colours but when I try to set the colour of the border I can use generic colours such as `blue` or `red` but I can't access any custom colours.

In addition when I try overriding `blue` or `red` to the hex values desired in the theme set up I still see the default colour corresponding to that name when used in the `<Border>...</Border>` component.

My provider is set up as follows:

```
const theme = {
  colors: {
    accent: '#99173C',
    darkBg: '#2E2633',
    darkAccent: '#555152',
    lightBg: '#EFFFCD',
    lightAccent: '#DCE9BE'
  },
  font: '"Avenir", serif'
};

const App = (props) => (
  <Provider theme={theme}>
      ...
      <Nav />
      ...
  </Provider>
);
```

The custom `<Nav />` component has the following source:

```
const Nav = (props) => (
  <Border bottom color={'accent'}>
    <Box width={1} bg={'darkBg'} p={2}>
      <Heading color={'lightBg'}>Soccermatic</Heading>
    </Box>
  </Border>
);
```

Note that the custom colours defined in the palette work in the children of `<Border>...</Border>`

Any advice would be great. Thanks in advance.

**Comment by jxnblk** [comment]
Yeah this is definitely a bug. I'll look into it in a little bit
