### ISSUE TITLE
1.0.0-7 Module not found: Can't resolve './tag'

### ISSUE THREAD

**Issue by gingerhendrix** [jxnblk/rebass#258]
Looks like something went wrong packaging the last release,  in the 1.0.0-7 package, the dist folder has '/Tag.js' instead of './tag.js' resulting in the error above.

**Comment by ferdinandsalis** [comment]
I just encountered the same error.

**Comment by jxnblk** [comment]
The module was renamed, but the `prepublish` script should rebuild dist on install. How are you installing Rebass?

**Comment by ferdinandsalis** [comment]
via npm. Could be git/mac case sensitivity issue, no?

**Comment by gingerhendrix** [comment]
Fixed in 1.0.0-8 thanks :)

**Comment by jxnblk** [comment]
Awesome, yeah might be some weirdness with npm publish/prepare changes as well. Please reopen if the problem persists
