### ISSUE TITLE
Using the drawer without funcup

### ISSUE THREAD

**Issue by vincentmvdm** [jxnblk/rebass#260]
Hi!

Thanks for the awesome work!

I am currently trying to implement the drawer and it seems like, besides importing the component, I need to 'set up' funcup to make it work. Is that indeed the case, and if so, is there a way to make the component open and close without funcup?

Thank you!

**Comment by jxnblk** [comment]
You don't need to use funcup (now renamed refunk), any state management will work since Rebass is completely stateless

**Comment by vincentmvdm** [comment]
Ah that is good to know! Thanks!
