### ISSUE TITLE
Request to add JSX to StoryBook

### ISSUE THREAD

**Issue by greg-murray-volusion** [jxnblk/rebass#262]
This is an excellent component library.  It would be cool if you added some extensions to the StoryBook, such as the [storybook-addon-jsx](https://github.com/Kilix/storybook-addon-jsx)

I made [changes in this fork](https://github.com/greg-murray-volusion/rebass/commit/83ff553421571165201761f5a59911c887a48e41), but had to override the display name, which then didn't work when there were multiple components in the same add.

![storybook](https://raw.githubusercontent.com/greg-murray-volusion/rebass/feature/add-jsx-to-storybook/stories/rebass-with-jsx.png)

Please let me know if you would like my help to pursue and fix this enhancement.

**Comment by greg-murray-volusion** [comment]
You may close this one.  I was running storybook locally and forgot about the [documentation section](http://jxnblk.com/rebass/components) of the website which accomplishes the same thing and more.

**Comment by jxnblk** [comment]
Thanks for the suggestion! I'll keep this open for now since I think improving the storybook can be helpful beyond what the docs do

**Comment by macklinu** [comment]
Wondering if this should be closed, since Storybook is no longer present in this codebase.
