### ISSUE TITLE
Row component has mx property set to -32 by default

### ISSUE THREAD

**Issue by RIP21** [jxnblk/rebass#264]
Title says everything :)

Here is the sandbox with reproduced bug and few examples

[![Edit kZB6mnv46](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kZB6mnv46)

Setting mx to 0 solves the problem, other fields not.

Also, wrapping with Provider and `theme.space = [0]` solve problem a little. Giving `mx = -3` which is still weird.

Provider also seems to have default theme, such as fonts etc. This must be described somewhere so people know defaults.

**Comment by ferdinandsalis** [comment]
@nfcampos My guess is that Row is meant to be used with Column which has as postive padding `px=3`. Which is a common pattern to achieve a grid with gutters and evenly sized columns.

**Comment by jxnblk** [comment]
Yeah, sorry the docs are sort of light around the components at the moment. As @ferdinandsalis said, `<Row />` is meant to be used with `<Column />` as a simple, no configuration sort of component. They both extend `<Flex />` and `<Box />` respectively, which are more generic and flexible.

The `<Provider />` is documented here: https://github.com/jxnblk/rebass#provider-

**Comment by nfcampos** [comment]
@ferdinandsalis I think you've mentioned me by mistake?

**Comment by ferdinandsalis** [comment]
@nfcampos sorry, yes! Happens quite easily …

**Comment by nfcampos** [comment]
@ferdinandsalis no problem!
