### ISSUE TITLE
Drawer raises "Warning: Unknown prop `position` on <div> tag" when `position="right"`

### ISSUE THREAD

**Issue by pletcher** [jxnblk/rebass#266]
It looks like `position` is getting passed directly to the underlying `<div>`: https://github.com/jxnblk/rebass/blob/master/src/components.js#L948.

Would adding `position` to [this blacklist](https://github.com/jxnblk/rebass/blob/master/src/clean-props.js#L15) cause any issues? (I've tried it locally and it _seems_ okay, but I admit I didn't poke it very much.)

**Comment by jxnblk** [comment]
It *could* be added to the Rebass blacklist, but this is more of an issue with styled-components' use of a whitelist (which is not very React-like and is likely to break in future React versions). I know that's something that's being worked on and would like to see how they decide to handle the issue on their end.

Technically, styled-components is only whitelisting HTML attributes, but it whitelists for all elements, so props like `width`, which is a valid HTML attribute for an `<img>` tag, still gets passed to a `<div>`. Adding Rebass-specific props to the blacklist solves some of the problem, but not all of it.

**Comment by pletcher** [comment]
I see what you mean, and I defer to your judgment here. I can close this issue and keep an eye on styled-components' progress, if you'd prefer.

It doesn't seem like anything is actually breaking (at least not the way I'm using `Drawer`), so I'm okay ignoring some console noise if there's an upstream fix incoming :)

**Comment by jxnblk** [comment]
Yeah I need to think on this a little bit. I'd prefer to keep the issue open since this will likely break in a future React version

**Comment by darArch** [comment]
Could this be re-opened?

I'm seeing `position='right'` not working on my drawer anymore, it displays at the left hand side of the window irrespective of which of the legal strings I pass as the property

**Comment by smith-kyle** [comment]
React is removing this warning in version 16
https://facebook.github.io/react/blog/2017/09/08/dom-attributes-in-react-16.html
