### ISSUE TITLE
Overlay shadow breaks in square browser 

### ISSUE THREAD

**Issue by mrlundis** [jxnblk/rebass#268]
Rebass looks awesome! 

I noticed a small bug when trying out the components in Storybook. The overlay background does not cover the entire screen if your bowser window is more or less square. It seems the cause is that the border radius extends to the box-shadow used to create the dimmed overlay background, leaving awkward uncovered areas in the corners. 

Removing the border radius or increasing the shadow spread fixes the problem.

![jxnblk com-rebass-stories--selectedkind overlay selectedstory default full 0 down 0 left 1 panelright 0](https://user-images.githubusercontent.com/58557/28322111-8b53f628-6bd5-11e7-8bbb-9d15f31845a6.png)

**Comment by jxnblk** [comment]
Yeah I'd consider that overlay effect a little experimental. There were issues rendering larger shadows in Safari so that whole component probably needs to be rethought

**Comment by jxnblk** [comment]
Closing this out since there have been some changes in v2, but feel free to open a new issue if this is still an issue
