### ISSUE TITLE
<Container width={500}> works <Container w={500}> does not

### ISSUE THREAD

**Issue by karland** [jxnblk/rebass#272]
`<Container width={500}>` works `<Container w={500}> does not`.

Is this an error or is this intended behavior because as an exception you are setting `max-width` with the `width`-prop.

**Comment by ferdinandsalis** [comment]
@karland see my explanation here https://github.com/jxnblk/rebass/issues/271.

**Comment by jxnblk** [comment]
Thanks, yes this is confusing looking back on it. It would probably be best to rename the container's prop to be `maxWidth`, since that's what it's setting, rather than overriding how the `width` and `w` props work
