### ISSUE TITLE
Warning: Unknown prop `h` on <hr> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by RIP21** [jxnblk/rebass#276]
I have component:

```
import React from 'react'
import { Divider as RDivider } from 'rebass'

const Divider = RDivider.extend`
  height: ${p => p.h || p.height};
`
export default props => <Divider {...props} />
```

And I'm get `Warning: Unknown prop `h` on <hr> tag. Remove this prop from the element.`
Is it a problem of styled-components (which is less likely) or Rebass? Can you maybe do a sanitation of all non valid props rather then passing them as it is causing this warning?

Working example:
[![Edit 0VRB7L5vv](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0VRB7L5vv)

**Comment by ferdinandsalis** [comment]
See comment here — https://github.com/jxnblk/rebass/issues/266#issuecomment-315909375

**Comment by RIP21** [comment]
@ferdinandsails thanks. I will close now then. Thanks.

**Comment by jxnblk** [comment]
@RIP21 Just a tip for syntax if you want to avoid the `as` keyword in imports and the extra component on export: Rebass exports an object with all the components, so you *could* rewrite your example as:

```jsx
import Rebass from 'rebass'
const Divider = Rebass.Divider.extend`
  height: ${p => p.h || p.height};
`
export default Divider
```

**Comment by RIP21** [comment]
@jxnblk small but very useful tip. Thanks a lot!
