### ISSUE TITLE
Values assigned to class when null

### ISSUE THREAD

**Issue by johnpolacek** [jxnblk/rebass#278]
For example, a Text element that does not have an alignment specified will generate a class with `text-align:null` -- see the [default Text Component](http://jxnblk.com/rebass/stories/?selectedKind=Text&selectedStory=Default&full=0&down=0&left=1&panelRight=0) in Storybook.

<img width="391" alt="screen shot 2017-07-21 at 2 52 05 pm" src="https://user-images.githubusercontent.com/179482/28479978-5141f7ea-6e24-11e7-96ce-59a46b7f52a5.png">

---

[This closed issue](https://github.com/styled-components/styled-components/issues/275) for styled components says:

> there are a couple of helpers that abstract this away quite nicely. I recommend you to go through those. You can also write the entire declaration into an interpolation instead to avoid it being overridden with an empty value.

**Comment by jxnblk** [comment]
Yeah, I think most of the helper functions return a full style object, I'll need to clean up the ones that only return values
