### ISSUE TITLE
Possibility of creating your own library of components

### ISSUE THREAD

**Issue by ferdinandsalis** [jxnblk/rebass#285]
Since you are exporting all the helpers and tools one could create their own version of a ui library. Was this your intention and do you see any problems with that?

**Comment by jxnblk** [comment]
I mean that's sort of the intention with this being open source. You can either consume the package as is, fork it, or just see how things were set up and steal ideas from it. That said I would be cautious about directly depending on any of the internal, undocumented APIs as those might change over time.

**Comment by ferdinandsalis** [comment]
@jxnblk thanks for answering. I will go ahead and use the internal api for now.
