### ISSUE TITLE
Select component padding being applied to parent div

### ISSUE THREAD

**Issue by jasonblalock** [jxnblk/rebass#286]
It looks as if going from 1.0.0-8 to 1.0.0 the Select component changed in that it received a container div. That div now receives all the styling props such as padding and margin instead of the select input itself. Is this expected behavior? 

I think I would expect adding padding to the Select would cause the select itself to have increased padding, not the parent div. Also adding the padding causes the select arrow to move out of position, I think because of the way the padding gets applied. Before the update, adding padding just made the select wider and taller and the arrow stayed in the correct position.

Example from your story book that shows the arrow offset and the padding not applied to the select

```js
<Select p={2} m={2}>
  <option>Hello</option>
  <option>Beep</option>
  <option>Boop</option>
</Select>
```

**Comment by jxnblk** [comment]
Hopefully this isn't an issue in v2, but feel free to open a new issue if it's relevant
