### ISSUE TITLE
Totally broken Select?

### ISSUE THREAD

**Issue by RIP21** [jxnblk/rebass#288]
```
.faqWSt select {
    padding: null;
    box-shadow: inset 0 0 0 1px gray2;
    border-radius: undefined;
}
```
It's a styles on Select component.
1.0.3 version.

Reproduction:
[![Edit PL8jAjN4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/PL8jAjN4)

**Comment by jasonblalock** [comment]
You need to wrap it in `<Provider/>`

Fixed:
https://codesandbox.io/s/KrAMk9LNY

**Comment by RIP21** [comment]
@jasonblalock Hmmm. I have mine in project wrapped in provider. But still box shadow is broken and weird gray2 inside. Padding etc is set but shadow is broken. :/

**Comment by jxnblk** [comment]
From the docs:

> To ensure Rebass's theme is properly configured, use the <Provider /> component at the root of your application.

Rebass is largely dependent on its theme and I wouldn't recommend using this library without the Provider component
