### ISSUE TITLE
Unknown prop `bg` on <div> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by jcsmesquita** [jxnblk/rebass#289]
Warning in console when using bg prop on Box.
```
<Flex wrap>
  <Box bg='blue'>
  </Box>
</Flex>
```
styled-components@2.1.1
rebass@1.0.3

**Comment by RIP21** [comment]
#276 
Already discussed many times. Unfortunately, there is no workaround and it seems to be by intent.

**Comment by jxnblk** [comment]
See #266
