### ISSUE TITLE
Suggestion: Component Ecosystem

### ISSUE THREAD

**Issue by sebasgarcep** [jxnblk/rebass#290]
This is not an issue with the library, but I discussion I wanted to have. Out of all the big component frameworks I've seen this is the only that embraces CSS-in-JS. As the fantastic article, [A Unified Styling Language](https://medium.com/seek-blog/a-unified-styling-language-d0c208de2660), helped me realize, this is a step forward in how we should build component-based UI systems because it allows extensibility of styles, which is the hardest thing to achieve with raw CSS.

Right now the scope of rebass is  somewhat limited in that it looks to provide barebones components, which is fine for some projects, but others need to move really fast and can't spend time reinventing the wheel. Of course, down the line, it is a bad move as you would accrue technical debt.

It doesn't have to be like this. We could create a new project apart from rebass that utilizes its primitives to implement more complicated components like date pickers and range sliders. And because we are essentially using CSS-in-JS these components would also be extensible.

So @jxnblk what are your opinions on the topic?

**Comment by johnpolacek** [comment]
I would not be surprised at all if @jxnblk is cooking up something in this regard. Rebass is pretty lightweight. It establishes a nice pattern of using styled components combined with some of his other libraries (Basscss, Styled System, Grid Styled). 

There may be better ways to extend Rebass, but here's a tiny, bare-bones example of how I'm currently creating custom components and theming:

https://github.com/johnpolacek/custom-rebass

I get what you are saying though. I think we want to get to a point where a theme.js file can be passed around across projects to set typography, color and scale. Today’s version of CSS Zen Garden I suppose.

**Comment by jxnblk** [comment]
Thanks for opening this, and sorry I never got around to responding. I think what you're describing is outside the scope of Rebass, but keep an eye on this https://github.com/standard-components/standard-components
