### ISSUE TITLE
accessing the theme

### ISSUE THREAD

**Issue by rsaccon** [jxnblk/rebass#293]
Just getting started with rebass. How can I access the theme from anywhere ? Does rebass provide any helper for that ?

my use case: I am extending a component:
```
const Item = styled(Container)`
    &:hover {
      background-color: #eee;
      cursor: pointer;
    }
  `;
```
so I would like to use a color key from the theme instead of hardwiring the color as I did above

**Comment by jxnblk** [comment]
The [`Rebass.Provider`](https://github.com/jxnblk/rebass/blob/master/src/Provider.js) component is a wrapper around styled-components' `ThemeProvider` (https://www.styled-components.com/docs/advanced#theming). If you're using the theme provider, you should be able to access the theme from props, e.g. `props.theme.colors.blue`. 

To use the theme outside of a React app, you can also manually import the theme `import { theme } from 'rebass'`

**Comment by rsaccon** [comment]
Thanks, found the `styled-components` `withTheme` helper, which does what I was looking for. Works great now.
