### ISSUE TITLE
Loading Custom Local Fonts

### ISSUE THREAD

**Issue by joshboldt** [jxnblk/rebass#294]
I am using NextJS with Styled-Components+Rebass for the UI in a static site (built using NextJS). I've been trying to inject a font into the page using the styled-components method of 'injectglobal' but it seems that Rebass is overwriting that every time with it's default theme parameters. Is there a better of loading a couple local fonts and getting Rebass to use them? Thanks!

**Comment by jxnblk** [comment]
If you want to change the font-family style that the Provider component sets, you'll want to pass it a `theme` prop with. `font` value.

```jsx
<Provider
  theme={{
    font: 'Georgia, serif'
  }}>
  <App />
</Provider>
```

If you're trying to load a webfont, you'll need to handle that on your end. Hope that helps!
