### ISSUE TITLE
<Heading children="Hello" /> vs <Heading>Hello</Heading>

### ISSUE THREAD

**Issue by karland** [jxnblk/rebass#295]
The docs and the code uses both `<Heading children='Hello' />` and `<Heading>Hello</Heading>`. I am not sure, but I think the `children` prop is undocumented.

I am aware of the children prop in React, eg. [http://mxstbr.blog/2017/02/react-children-deepdive/](http://mxstbr.blog/2017/02/react-children-deepdive/)

However, I cannot find an explanation when to use the children prop, whether it only allows strings and when it should be used as best practise in the context of Rebass.

Can someone help? Thanks.

**Comment by jxnblk** [comment]
The two are interchangeable in React. I tend to use the prop when it seems to aid readability, but often it's better to nest
