### ISSUE TITLE
Customize Color Palette

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/rebass#296]
I saw you are generating the palette based on a fixed value: https://github.com/jxnblk/rebass/blob/master/src/theme.js#L38

Could be awesomeness be possible setup the value and generate the color pallete.

For example, generate the palette if the `colors` provider is an string instead of an object of colors:

```jsx
<Provider theme={{colors:'#19b5fe'}}'></Provider>
```

**Comment by jxnblk** [comment]
You can do this with the `palx` package:

```js
import Rebass from 'rebass'
import palx from 'palx'

const colors = palx('#f00')

// <Rebass.Provider theme={{ colors }} />
```

Optionally you can flatten the object like here: https://github.com/jxnblk/rebass/blob/master/src/theme.js#L40-L52

But the `color` prop accepts dot notation if you prefer that approach: `<Button color='red.3' />`

**Comment by Kikobeats** [comment]
maybe we can integrate `flattened` inside `palx`?
