### ISSUE TITLE
Fixed and null values 

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/rebass#297]
When a value is not defined in the API, then the prop is added with `null` value.

From your example at rebass:

```
<div>
	<Button
		onClick={e => update(toggle('fixed'))}
		children='Toggle Fixed'
	/>
	{fixed && (
		<Fixed
			m={2}
			p={3}
			bg='green3'
			z={1}
			right
			bottom>
			Hello
		</Fixed>
	)}
</div>
```

It's is rendered as:

<img width="486" alt="screen shot 2017-08-05 at 15 09 32" src="https://user-images.githubusercontent.com/2096101/28995685-1deeac3a-79f0-11e7-9bb2-c9c6a302774f.png">

Ideally, don't add the prop if value is not present

Code related: https://github.com/jxnblk/rebass/blob/a3f9aea1136c2befa44cb8e8fd5d694ca7de4c87/src/components.js#L869

**Comment by jxnblk** [comment]
This would have been fixed in #281, but was giving #256 a chance to handle it. Since it wasn't merge in, this should be addressed in another PR

**Comment by Kikobeats** [comment]
Hmmm in general I think all the `null` ternaries are potentially wrong:
https://github.com/EddiG/rebass/blob/b61a226f7bf681cc45ab42a84936bbb15753acb2/src/components.js#L562

**Comment by Kikobeats** [comment]
A simple way to remove `null`props is using [lodash.groupBy](https://lodash.com/docs/4.17.4#groupBy):

```
style: groupBy(props => ({
  position: 'fixed',
  top: props.top ? 0 : null,
  right: props.right ? 0 : null,
  bottom: props.bottom ? 0 : null,
  left: props.left ? 0 : null,
  zIndex: props.z
  )
```

But it introduces a dependency; I'm not sure if you want this, or you prefer build an internal helper for that.

**Comment by jxnblk** [comment]
Passing null as an argument should be fine to remove the positioning properties, they just need to be updated to be inline with the other component helpers

**Comment by jxnblk** [comment]
Closing this, but please open a new issue if this is still an issue
