### ISSUE TITLE
Classname prop

### ISSUE THREAD

**Issue by adavkay** [jxnblk/rebass#30]
Would it not be nice to be able to pass down classNames on components so you don't have to wrap the components with another block just to put a className on it? 

For example:

```
<Toolbar className="Nav" color="white"></Toolbar>
```

instead of:

```
<nav className="Nav">
  <Toolbar color="white"></Toolbar>
</nav>
```

I would be willing to submit a PR to address this if this is a legitimate issue and not just how you explicitly designed the components.

Thanks!

Andy

**Comment by chrislloyd** [comment]
Hey Andy. That tends to be a common pattern but ultimately breaks style
purity of rebass components. If a user can add any style they want to a
component it's impossible for the component author to be able to change the
component knowing they won't break anything. Wrapping components may seems
like your adding superfluous divs but it's actually making your application
much more robust.

**Comment by noxplode** [comment]
Thanks that makes sense. However, say I wanted to give the `Toolbar` component a white background how would I go about doing that without overriding the css?

**Comment by chrislloyd** [comment]
You can pass `color: "white"` in as a prop: https://github.com/jxnblk/rebass/blob/master/src/Toolbar.jsx#L19

**Comment by noxplode** [comment]
Sorry one last question: won't the text color still be white though?
https://github.com/jxnblk/rebass/blob/master/src/Toolbar.jsx#L18

**Comment by chrislloyd** [comment]
Yep. I'd either create a PR to customize the bg-color and the text color independently or create your own toolbar component seeing as it's so simple :)

**Comment by noxplode** [comment]
Ok thanks for your help Chris!

**Comment by jxnblk** [comment]
I generally agree with @chrislloyd on this one. Passing `className` as props breaks the encapsulation of styles in the component. That said, future versions of this repo should make the components more flexible, especially in regards to colors and theming.
