### ISSUE TITLE
Unknown prop borderWidth on <div> tag

### ISSUE THREAD

**Issue by Hilaryous** [jxnblk/rebass#301]
Seeing warning in console when using borderWidth on a `<Border/>` component.
Border is defined like so:

```
<Flex>
  <Box>
    <Border bottom borderWidth={2}>
       ...
    </Border>
  </Box>
</Flex>
```

Error Message is: 
<img width="416" alt="screenshot 2017-08-08 11 21 42" src="https://user-images.githubusercontent.com/5042071/29085208-d3a53fde-7c2b-11e7-9de2-071d114f06f6.png">

**Comment by jxnblk** [comment]
See #266
