### ISSUE TITLE
Color/Selected Color in TabItem

### ISSUE THREAD

**Issue by sponge** [jxnblk/rebass#304]
I don't see any clear way to change the color or the active color of a TabItem. bg works, but color seems to keep it white and blue. What's the recommended way to change the active and hover colors of a TabItem?

**Comment by Kikobeats** [comment]
Currently is not configurable, I did a PR for that https://github.com/jxnblk/rebass/pull/307

**Comment by johnpolacek** [comment]
You can create your own versions of Rebass components using the same patterns that @jxnblk does. I made a bare bones example of one way to do this at https://github.com/johnpolacek/custom-rebass

**Comment by sponge** [comment]
Thanks for the feedback! Just for the record, this is what I eventually stumbled my way onto working, and it's working well enough for my needs:

```
const RedTabItem = styled(TabItem)`
&:hover {
  color: white;
  border-bottom: 3px solid white;
}
color: ${props => props.active ? 'white' : '#baabab'};
border-bottom: 3px solid ${props => props.active ? '#d22730' : 'transparent'};
`
```

but agreed that activeColor should probably be a prop.
