### ISSUE TITLE
Improve Bundle Size?

### ISSUE THREAD

**Issue by mjsisley** [jxnblk/rebass#308]
Hey, Rebass is awesome! It is pretty heavy (which makes sense) at 172.7kb raw as measured by the vscode plugin: import cost. If you think it is somewhat stable with it's usage of `styled-components` and your helper `styled-` libraries now, maybe trying to trim down the bundle size is worth doing now.

I will try to compile a list of potential low hanging fruit within the dependencies.
* https://github.com/jxnblk/palx/issues/6: Potential 10kb savings: replace chroma with [color](https://github.com/Qix-/color) in palx

Of course, feel free to close if you don't think that it is that big of a deal for rebass, you plan for more substantial iteration, or whatever else. Perhaps `rebass` is for when bundle sizes don't matter and `csx` is for when they do.

**Comment by Kikobeats** [comment]
BTW, `import-costs` is a lie because it doens't take in consideration the rest of your dependencies.

A better metric: https://bundlephobia.com/result?p=rebass@1.0.4

**Comment by jxnblk** [comment]
Closing this due to the v2 rewrite
