### ISSUE TITLE
Styling Workflow

### ISSUE THREAD

**Issue by der-lukas** [jxnblk/rebass#309]
Hey!

I'm thinking of moving from ReactStrap to Rebass, because I don't want to have Bootstrap and styled-components alongside of each other, since it's two completely different approaches and will ultimately lead to chaos (some components styled via CSS-files, some inside the component... => no single source of truth)

I'm wondering how I would go about styling the components in Rebass. 

Do I really need to do something like `export const CustomButton = styled(Button)` for every component to adjust the styles to fit our needs? Theming via `Provider theme="{theme}"` seems also very basic. Also I lose th

As I'm pretty new to React and used to writing SASS and using Frameworks like Bootstrap, my previous workflow was (obviously):

1. Customize Bootstrap theme
2. Create custom components for everything else

How would I go about it now with Rebass/Styled Components?

**Comment by followbl** [comment]
hey @der-lukas 

did you have a look here @ http://jxnblk.com/rebass/theming for basic theming needs? 

a simple anchor tag styled with rebass would look like so

```
import React from 'react'
import styled, { keyframes } from 'styled-components'
import { Message } from 'rebass'
import { bounceInDown } from 'react-animations'

const bounceInDownAnimation = keyframes`${bounceInDown}`
const StyledMessage = styled(Message)`
  max-width: 500px;
  min-width: 300px;
  padding: 0;
  position: fixed;
  z-index: 3;
  top: 100px;
  right: 0;
  padding: 0 1em;
  left: 0;
  margin: 0 auto;
  justify-content: center;
  color: ${props => !props['data-success'] ? props.theme.colors.red : props.theme.colors.green};
  background-color: ${props => !props['data-success'] ? props.theme.colors.lightred : props.theme.colors.lightgreen};
  border: 1px solid ${props => !props['data-success'] ? props.theme.colors.red : props.theme.colors.green};
  border-radius: 4px;
  animation: ${bounceInDownAnimation} 1s cubic-bezier(0.165, 0.84, 0.44, 1);
`

const MessageComponent = function (props) {
  if (!props.text.length) return null
  return (
    <StyledMessage data-success={props.success}>
      {props.text}
    </StyledMessage>
  )
}

export default MessageComponent
```
