### ISSUE TITLE
Theme not passed as props

### ISSUE THREAD

**Issue by tafelito** [jxnblk/rebass#311]
Hi, I',m trying to use of the theme colors within a component but the theme props is not present. 

This is what i'm doing

```js
import { Provider, Heading } from 'rebass';

const palx = require('palx');
const colors = palx('#CC1710');

const Title = props => <Heading color={props.theme.colors.base}>Hello</Heading>;

const App = props => (
  <Provider theme={{ colors }}>
    <Title />
  </Provider>);
```

And the error says

`Uncaught TypeError: Cannot read property 'colors' of undefined`

React Version 15.5.4
Rebass Version 1.0.4

Am I doing something wrong?

Thanks

**Comment by tafelito** [comment]
Sorry, not an issue

**Comment by chriscarpenter12** [comment]
@tafelito I am having the same issue trying to start using rebass. How did you solve this? I feel like I'm missing something simple. I have basically you're same setup.

**Comment by tafelito** [comment]
If you wanna access the color within a styled component you do it through the props, like props.theme.colors.xxx but if you are trying to use it within a component. you just use the color code xxx, so it would be something like <Text color="xxx" />

Hope it helps

**Comment by chriscarpenter12** [comment]
Ah that makes sense. I was trying props.theme.color on the component itself. I got it working thank you!
