### ISSUE TITLE
Tooltip may need left, center, right prop

### ISSUE THREAD

**Issue by karland** [jxnblk/rebass#312]
I have 

```JSX
<Tooltip w={1/10} text="Personal Contact">
  <Text bold right>
    ♡
  </Text>
</Tooltip>
```

The result looks like

![2017-08-18 13 49 13](https://user-images.githubusercontent.com/4803370/29457856-8e4ecf9c-841c-11e7-9d3e-c7b9602bc57b.jpg)

The default tooltip
1. reaches over the right border of the app (app background is red)
2. the little triangular is centered 

A left, center, right prop could align the tooltip and place the triangular at the corresponding sides. What do you think?

**Comment by jxnblk** [comment]
Sorry for not responding, but I'd prefer to keep the Tooltip here simpler and not support that functionality. There are a few other good tooltip components out there, and I'd suggest using one of those if this one doesn't suit your needs
