### ISSUE TITLE
Select box does not open when clicked on triangle

### ISSUE THREAD

**Issue by karland** [jxnblk/rebass#314]
The `<Select />` box does not open when one exactly clicks on the black triangle. This is different from the HTML default behaviour. No big deal, but maybe a little bit irritating for users that they have to click next to the triangle. In input fields such as `<input type="number">` one has to click on the triangles for them to fulfil a function, e.g. to count the number up and down.

**Comment by jxnblk** [comment]
Closing this since I don't think this is an issue in v2 anymore
