### ISSUE TITLE
More than one font-family

### ISSUE THREAD

**Issue by xinranwang** [jxnblk/rebass#316]
Is there a way that I can specify a font-family to use for `Text`? Or maybe just serif and sans?

**Comment by jxnblk** [comment]
You can extend the Text component, e.g.

```
const Serif = styled(Text)`
  font-family: Georgia, serif;
`
```

**Comment by maxdeviant** [comment]
@xinranwang If you're satisfied with the answer here would you mind closing out this issue?

**Comment by Kikobeats** [comment]
At `rebass@2` you have more than one font family, so yep this could be closed @jxnblk
