### ISSUE TITLE
BlockLink component overrides color set with color prop

### ISSUE THREAD

**Issue by selrond** [jxnblk/rebass#320]
I've noticed that `<BlockLink color='red' />` doesn't change color, instead it uses its default `color: inherit`. 
When inspected, the desired color does show up, but it's overridden by `color: inherit`
I suppose it's a bug since color is a general purpose prop in Rebass.

**Comment by jxnblk** [comment]
Duplicate of #321

**Comment by selrond** [comment]
@jxnblk sorry, haven't found that one. Closing.
