### ISSUE TITLE
`color` on BlockLink is overridden by `color: inherit;`

### ISSUE THREAD

**Issue by gregwym** [jxnblk/rebass#321]
When setting `color `on a `BlockLink`, it is overridden by the `color: inherit;` style from the component itself. 

```
<BlockLink to={`/some/url`} color="white">GO</BlockLink>
```

![image](https://user-images.githubusercontent.com/510089/29891200-1d90ad40-8d7f-11e7-9163-e71139d230d0.png)

**Comment by jxnblk** [comment]
Good catch, thanks! The color value should be set in the `props` object instead of the `style` object – feel free to open a PR otherwise I'll try to patch this in the next release

**Comment by MiguelMadero** [comment]
That's odd, I was expecting the rules to be added in the order they're defined and the ones from props to be defined last....

**Comment by MiguelMadero** [comment]
Oh, ignore me, for some reason GH wasn't showing me the activity and I just replied to the original issue. I see this is fixed and what the issue was. 👍 thanks for addressing this so soon.

**Comment by gregwym** [comment]
@jxnblk I opened #323 to fix this issue, could you please take a look?
