### ISSUE TITLE
Select styling issues

### ISSUE THREAD

**Issue by francip** [jxnblk/rebass#327]
In SelectBase, the down arrow for the Select is styled with margin of 12px, and the only way I could get it to render properly centered with the text of the select was to set p={1}. Everything else looks bad.

**Comment by francip** [comment]
Sorry, I'll do this later this month. However, the issue turned out to be that I didn't have a theme <Provider>. My expectation was that if I don't put <Provider> element, Rebass would create a default one somehow.

**Comment by jxnblk** [comment]
The Select component in v2 should be a little more robust in situations like this so closing this out
