### ISSUE TITLE
How to get Input value?

### ISSUE THREAD

**Issue by abraaobuenotype** [jxnblk/rebass#328]
hello

i have

<Input ref={x => {this._input = x} />

how to get the value? like:

console.log(this._input.value);

thanks

**Comment by vicbell** [comment]
You can put the value in the state when `onChange` and get it from the state.
```javascript
<Input 
value = {this.state.value} 
onChange = {
(e) => {
    this.setState({ foo: e.target.value }); 
    console.log(this.state.foo); 
}}
/>
```

**Comment by abraaobuenotype** [comment]
thank you so much
