### ISSUE TITLE
Inconsistent button behavior between safari & chrome 

### ISSUE THREAD

**Issue by walleXD** [jxnblk/rebass#333]
Hi,

`:focus` & `:active` for button doesn't behave in the same way between chrome & safari as in chrome box shadow is added but it remains even after the button isn't active while this doesn't happen in safari.

![rebass](https://user-images.githubusercontent.com/6826840/30666457-61a00c3e-9e22-11e7-923d-2190e3212f6f.gif)
Chrome on left & safari on right

What is the best way to make sure that chrome behaves the same way as safari?

**Comment by jxnblk** [comment]
I believe what you might be seeing is focus state, but yes there will likely always be browser inconsistencies. My advice is don't lose any sleep over stuff like this :)
