### ISSUE TITLE
Textarea does not respect fontSize

### ISSUE THREAD

**Issue by smith-kyle** [jxnblk/rebass#336]
`Textarea` does not use the `f` or `fontSize` prop and instead is statically set to "inherit". If this isn't intentional I think we could pull the fontSize from the theme in the components.js file to fix it

https://github.com/jxnblk/rebass/blob/e5a17b9cf5839d18aaaa7f0b1ae2b033f245a8b8/src/components.js#L391

**Comment by jxnblk** [comment]
Should be fixed in v2
