### ISSUE TITLE
Space array rendering as pixel value, not the key's value.

### ISSUE THREAD

**Issue by callumflack** [jxnblk/rebass#338]
Anything after the first item in the array is rendered as a pixel value, not the key's value.

Example: https://codesandbox.io/s/jv8j3pq0v3

`<Box is="section" py={[4, 6]} mx={[1, 5]}>`

At min-width 40em, py is 6px and mx is 5px.

**Comment by zentuit** [comment]
@callumflack : In that example, you're not wrapping your app with the rebass `Provider` component. That means the rebass theme values aren't used and its falling back to the styled-system default space settings:
```
const space = [
  0,
  8,
  16,
  32,
  64
]
```
This is what that snippet should look like:
```
import React from "react";
import { render } from "react-dom";
import { Provider, Flex, Box } from "rebass";
import Hello from "./Hello";

const styles = {
  fontFamily: "sans-serif",
  textAlign: "center"
};

const App = () => (
  <Provider>
    <div style={styles}>
      <Box is="section" py={[4, 5]} mx={[1, 5]}>
        <Hello name="CodeSandbox" />
        <h2>Start editing to see some magic happen {"\u2728"}</h2>
      </Box>
    </div>
  </Provider>
);

render(<App />, document.getElementById("root"));
```

**Comment by callumflack** [comment]
Thanks @zentuit 

I'll close, delete and then burn this issue…
