### ISSUE TITLE
why is this built w/ styled-components instead of cxs?

### ISSUE THREAD

**Issue by Jascha-Sundaresan** [jxnblk/rebass#339]
I've been playing around with this for a while but recently discovered cxs. (awesome work btw)

It seems like the only thing that'd need to be changed is the hoc.

Is there a reason you didn't do this?

**Comment by lachlanjc** [comment]
I would love a separate version of this with cxs! I think the only reason is that styled-components is widely used and cxs, though I much prefer it, isn’t used by so many apps.

@jxnblk actually built a branch in December using cxs: https://github.com/jxnblk/rebass/tree/cxs

**Comment by Jascha-Sundaresan** [comment]
it seems that rebass has come a long way since then.  His current tooltip is a lot cleaner.
I ported the current one to cxs and it only took a tiny bit of changing.

**Comment by jxnblk** [comment]
I'll be supporting other libraries in addition to styled-components in a future version. Currently styled-components is probably the most widely used one, so wanted to start there.

**Comment by Jascha-Sundaresan** [comment]
yeah but cxs > styled components...

No need to be humble when your work is fantastic, @jxnblk
