### ISSUE TITLE
InputRange Should Have a Callback Function

### ISSUE THREAD

**Issue by geirman** [jxnblk/rebass#34]
Firstly, love what you've done here and really appreciate your efforts. I can see this being very useful. I'd love to see a react-native version. 

For things like InputRange, shouldn't there be a callback function, something like `onValueChange={ val => console.log(val) }` to report the value back up to the parent component?

**Comment by jxnblk** [comment]
Thanks! All the form components *should* pass props down to the correct element, so you'd just use the normal React `onChange` prop. That said, I haven't written browser tests for this yet, but working on it.

E.g.
```jsx
<InputRange
  name='foo'
  label='Foo'
  value={foo}
  onChange={handleChange} />
```
