### ISSUE TITLE
[Question] What is rebass.hoc

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/rebass#343]
Reviewing live-doc code I see this:

https://github.com/jxnblk/live-doc/blob/831ed9af40e489a3585504bc621cee34f6cc3e43/lib/Live.js#L21

Why you are using it in these specific components? why is it necessary?

🤔

**Comment by Jascha-Sundaresan** [comment]
the hoc adds all the styled-system goodies. that's why he can do 
`<Preview w={[ 1, 1, 1/2 ]} />`

**Comment by Kikobeats** [comment]
oh damn! so useful, It should be documented

**Comment by jxnblk** [comment]
It'll be replaced with something else soon – generally I don't want to document private APIs

**Comment by karland** [comment]
@jxnblk Can you already reveal some of your plans? That would be great. Thanks.

**Comment by Kikobeats** [comment]
Looks like at rebass v2 hoc is not available.

Any way to have the same effect? is useful add all the styled-system goodies in one line

**Comment by jxnblk** [comment]
Rebass v2 uses [system-components](https://github.com/jxnblk/styled-system/tree/master/system-components) – you can create your own wrappers or base components to achieve what the previous HOC did
