### ISSUE TITLE
Avatar responsive values

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/rebass#344]
Currently `<Avatar />` component doesn't have a responsive API.

Expected behavior:

```jsx
<Avatar
	size={[16, 32, 64]}
	src='https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=2048&q=20'
/>
```

**Comment by jxnblk** [comment]
You should be able to achieve a similar effect with using em units on the Avatar and setting fontSize responsively on the parent

**Comment by jxnblk** [comment]
Since v2 uses the latest styled-system, I don't think this is an issue anymore
