### ISSUE TITLE
Cannot style track in Progress component

### ISSUE THREAD

**Issue by christiannaths** [jxnblk/rebass#345]
The track element (`::-webkit-progress-bar`) cannot be styled using `bg=` prop as described in the documentation. Adding a value here, either a theme color key name or CSS color value (hex or keyword) seems to have no effect. The component always uses the default prop value `grey2` instead of passing along the value specified. If the theme color object has a `grey2` key, the component uses that color as expected. If the theme does not have that key, the web browser default is used (also expected).

## Steps To Reproduce:

- `create-react-app example && cd example && yarn add rebass`
- add `import { Provider, Progress } from 'rebass';` to a component
- add the component:
```js
<Provider>
  <Progress value={1 / 3} bg="#ff000" />
</Provider>
```

---
I am, however, able to control the styles of the track by extending the component
```js
import styled from 'styled-components';

const MyProgress = styled(Progress)`
  &::-webkit-progress-bar {
    background-color: #ff000;
  }
`;
```

Possibly related to #322

**Comment by jxnblk** [comment]
Sorry for the delay, but due to the nature of this type of styling, extending the component is probably the best way to handle what you've described
