### ISSUE TITLE
Use theming library

### ISSUE THREAD

**Issue by goodmind** [jxnblk/rebass#346]
Use https://github.com/iamstarkov/theming to support themes in other jss solutions, not only styled-components

**Comment by johanneslumpe** [comment]
Right now this library uses styled components directly within `components.js` to create view primitives. As long as that is the case what would the gain from using `theming` be?

**Comment by goodmind** [comment]
The case is for using rebass without other CSS-in-JS libs

**Comment by johanneslumpe** [comment]
@goodmind What it meant was that rebass does not only rely on styled components for theming but also to create all its core components. So this would require more work than than just starting to use `theming`. https://github.com/jxnblk/rebass/blob/master/src/hoc.js would need to be updated to a version which allows users to either provide their own implementations or rebass would have to provide multiple implementations, one for each supported css-in-js library.

Not saying that it's a bad idea to get rebass to a point where it can be used with other libraries, just that it is more work than just using `theming`.

**Comment by goodmind** [comment]
@johanneslumpe I think `theming` is enough for themes only

**Comment by johanneslumpe** [comment]
@goodmind Maybe I'm misunderstanding what you are trying to do then. I figured that you wanted to use the components you get with `rebass` with a different library than styled components.

**Comment by jxnblk** [comment]
If you're looking for something that provides Rebass-like props for any css-in-js library, see https://github.com/jxnblk/styled-system

Since styled-components has its own theme provider and context, Rebass is currently using that
