### ISSUE TITLE
Is there a way to view available props types for each component?

### ISSUE THREAD

**Issue by protoEvangelion** [jxnblk/rebass#347]
Can we view available props for each component without going into source?

https://github.com/jxnblk/rebass/blob/master/src/components.js

I've looked everywhere in the docs and in storybook but couldn't find **all** acceptable props for each component.

**Comment by romainquellec** [comment]
I agree. I think we shoud work on documentation more.
This project is based on styled-system and grid-styled which make it more complicated to get all the informations.

An improvement on storybook can be good for documentation use.

**Comment by pungggi** [comment]
Yes absolutely something like this would help: 
![grafik](https://user-images.githubusercontent.com/5635709/38010130-f6e7ce84-3257-11e8-925f-2c0f316f2d0d.png)

**Comment by jxnblk** [comment]
With v2 the component doc is now generated based on the prop types. Hopefully this doc will get a little better over time:

https://github.com/jxnblk/rebass/blob/master/docs/components.md
