### ISSUE TITLE
Can it be used with Vue?

### ISSUE THREAD

**Issue by jitendravyas** [jxnblk/rebass#348]

**Comment by maxdeviant** [comment]
@jitendravyas Rebass is based on React and styled-components, so it won't work with Vue.

**Comment by xiaoheng21** [comment]
you can create it use vue.

**Comment by petitkriket** [comment]
if you happen to stumble on this issue, chakra-ui vue rely on styled-system and have some close primitives [check it out](https://vue.chakra-ui.com/style-props)
