### ISSUE TITLE
npm snafu

### ISSUE THREAD

**Issue by forresto** [jxnblk/rebass#35]
I installed and poked a bit before seeing that 1.5 (from `npm install rebass` and github) doesn't match the docs (0.2.0-beta7). Then I had to `npm install colors.css`

**Comment by jxnblk** [comment]
Not sure what's happening on your end. 0.2 is a complete rewrite and introduces breaking changes from 0.1. All the `-beta` releases were published with the `latest` tag, so a clean `npm i rebass` should grab the latest.

**Comment by forresto** [comment]
All good with 0.2.0 :bow:
