### ISSUE TITLE
Ability to blacklist custom props created via `createComponent`

### ISSUE THREAD

**Issue by goldcaddy77** [jxnblk/rebass#350]
I'm using `createComponent` to create new items for my component library that take in custom params and am getting:

```
Unknown props `bg`, `borderColor` on <div>
```

2 things here:

- `bg` is in the blacklist, but it's somehow leaking through, any idea how?
- `borderColor` is a custom attribute i've added and handle in my component.  Could we add an additional option in `createComponent` to blacklist additional params?

Code:

```typescript
import { bool, number, string } from 'prop-types'
import { Flex as RebassFlex, createComponent, FlexWithExtraProps, util } from 'rebass';

import { COLORS } from '../../styles';

const flexOptions = {
  name: 'Flex',
  type: RebassFlex,
  props: { },
  style: (props: any) => {
    const borderDefaults = {
      borderColor: COLORS.black,
      borderRadius: util.px((props.theme && props.theme.radius) || 4),
      borderStyle: 'solid',
      borderWidth: util.px(1),
    }

    let propValues = {} as any
    if(props.borderColor || props.borderRadius || props.borderStyle || props.borderWidth) {
      propValues = {...borderDefaults}

      if (props.borderColor) { propValues.borderColor = props.borderColor }
      if (props.borderRadius) { propValues.borderRadius = util.px(props.borderRadius) }
      if (props.borderStyle) { propValues.borderStyle = props.borderStyle }
      if (props.borderWidth) { propValues.borderWidth = util.px(props.borderWidth) }
    }

    if (props.expand) {
      propValues.flex = '1 1 auto'
    }

    return propValues
},
  propTypes: {
    borderColor: string,
    borderRadius: number,
    borderStyle: string,
    borderWidth: number,
    expand: bool
  }
};

export const Flex = createComponent(flexOptions) as React.StatelessComponent<FlexWithExtraProps>

```

**Comment by lachlanjc** [comment]
👍 to both. I’m seeing `color` and `bg` in the DOM (though they also apply the style). And not needing to wrap certain components (especially Button) with custom utilities would be great.

**Comment by goldcaddy77** [comment]
Solutions:

> bg is in the blacklist, but it's somehow leaking through, any idea how?

Looks like this is because [grid-styled](https://github.com/jxnblk/grid-styled/blob/master/src/remove-props.js) has a different blacklist

> borderColor is a custom attribute i've added and handle in my component. Could we add an additional option in createComponent to blacklist additional params?

There are a [bunch of solutions](https://github.com/styled-components/styled-components/issues/439#issuecomment-307335814) to this problem that seem easy enough, so you can just roll your own
