### ISSUE TITLE
Cannot change transition time on Button component

### ISSUE THREAD

**Issue by protoEvangelion** [jxnblk/rebass#351]
Just started using rebass and am trying to customize the Button component.

All I am trying to do is **increase the duration of the transition on hover.**  Am I doing this wrong or is this a bug?

```js
import { Button as Btn } from 'rebass'
import styled from 'styled-components'

const Button = styled(Btn)`
  transition: background 1s;
  cursor: pointer;
  &:hover {
    transition: background-color 1s;
  }
`
```

The **transition duration and property** is showing up as expected in dev tools on the button element, but has no effect on hover.

![image](https://user-images.githubusercontent.com/20076677/32420142-ade9cfd0-c23a-11e7-9dc7-ef0110a8ea9c.png)

However, when I add the **background color** to the css rather than passing it in as a prop like `<Button color: 'blue' ...` it works:

```js
  &:hover {
    transition: background-color 1s;
    background: blue;
  }
```

**Comment by maxdeviant** [comment]
@protoEvangelion Does it work if you do it this way?

```js
import { Button as Btn } from 'rebass'
import styled from 'styled-components'

const Button = Btn.extend`
  transition: background 1s;
  cursor: pointer;
  &:hover {
    transition: background-color 1s;
  }
`
```

([source](https://www.styled-components.com/docs/basics#extending-styles))

**Comment by protoEvangelion** [comment]
No that does not work :(
