### ISSUE TITLE
Add some project using Rebass

### ISSUE THREAD

**Issue by romainquellec** [jxnblk/rebass#355]
I'm looking for example for Rebass components used in real project. (ofc, i'm using github search for that).
@jxnblk, can you call for projects using yours on twitter & Github ? Thanks.

**Comment by lachlanjc** [comment]
https://github.com/jxnblk/rebass/wiki/Projects-using-rebass

🙂

**Comment by maxdeviant** [comment]
Perhaps we could get this added somewhere in the README so it's a bit more visible?

**Comment by romainquellec** [comment]
Thank you. I'm closing this now.
