### ISSUE TITLE
Default values for component props

### ISSUE THREAD

**Issue by dziamid** [jxnblk/rebass#356]
I want to define all styles using Styled Components api rather than special `bg` & `color` props. If I omit the color\bg prop, the default values will override any styling from Styled Components. 
For example:
```
import {Card} from 'rebass';
const PinkCard = styled(Card)`
  background-color: pink;
` 
<Card /> renders a white card
<PinkCard /> still redners a white card ?
<PinkCard bg="pink" /> renders a pink card though, which make things unnecessarily complex for me
```
The way i'm address this right now is by resetting props in my base components, e.g.
```
import {Card as BaseCard} from 'rebass';
import {defaultProps} from 'recompose';
export const Card = defaultProps({bg: undefined, color: undefined}}(BaseCard);
```
I suspect there should be a easier way to set default bg, color and other props values.
Looks like [people](https://github.com/jxnblk/rebass/issues/345) expect styled components styles to take precedence over the props.

**Comment by maxdeviant** [comment]
Is there a particular reason you want to style using `styled-components` rather than using the Rebass props? Seems like it defeats the purpose of using Rebass in the first place.

If you want to change the default props for a component, you can do this:

```js
import { Card } from 'rebass'

const PinkCard = styled(Card)``

PinkCard.defaultProps = {
  bg: 'pink'
}
```

**Comment by jxnblk** [comment]
Sorry for the delay, but props are meant to be used wherever applicable, since these are React components. An alternative to the above suggestion could look something like this:

```jsx
const PinkCard = props =>
  <Card
    {...props}
    bg='pink'
  />
```

**Comment by djgrant** [comment]
This caught me out too. The solution was to import the component from `rebass/styled-components`

Before
```
import { Box } from 'rebass';
```

After
```
import { Box } from 'rebass/styled-components';
```
