### ISSUE TITLE
Link to docs gives 404 when opened with 'open link in new tab'

### ISSUE THREAD

**Issue by rm8x** [jxnblk/rebass#357]
Steps to reproduce: 1. Open http://jxnblk.com/rebass. 2. Navigate to http://jxnblk.com/getting-started via 'open link in new tab'.  3. A wild 404 appears!

Thanks for your work on this and related libs.

**Comment by macklinu** [comment]
I can see the 404 you mention, but the Getting Started page is located at http://jxnblk.com/rebass/getting-started and is properly linked to the Documentation button on the home page of http://jxnblk.com/rebass/.

I think this can be closed unless I'm misunderstanding the original issue.
