### ISSUE TITLE
position for Drawer doesn't work?

### ISSUE THREAD

**Issue by w-jiang** [jxnblk/rebass#358]
I'm trying to change the position for Drawer but it always goes to the default (left). It's broken in my app and also http://jxnblk.com/rebass/components/Drawer but works in http://jxnblk.com/rebass/stories/?selectedKind=Drawer&selectedStory=Bottom&full=0&down=0&left=1&panelRight=0 so I'm just wondering if I'm using it incorrectly in my app...

**Comment by Nickersona** [comment]
I'm experiencing the same issue. I'm trying to figure out what's going on and all that I've been able to  find out for sure is that, whatever the default position prop is set to in `src/component.js` is what every instance of Drawer gets no matter how the Component is configured at implementation time.

I suspect it's something to do with the various HOC's that wrap the components when they're run though the `src/create-component.js` script. But I'm having a really hard time wrapping my head around what's happening there to effectively debug. @jxnblk You have any ideas?
