### ISSUE TITLE
React Router

### ISSUE THREAD

**Issue by gigavinyl** [jxnblk/rebass#36]
How does one create a NavItem with a react-router Link? Excuse my n00b-ness, I'm quite new to react.

**Comment by jxnblk** [comment]
No worries. I haven't documented that very well yet. The basic way is something like this:

```jsx
import { NavItem } from 'rebass'
import { Link } from 'react-router'

const MyComponent = () => (
  <div>
    <NavItem
      to='/'
      Component={Link}
      children='Home' />
  </div>
)
```

I haven't written any tests for this specific case, but this *should* work.

If you'd like to use the NavItem styles throughout your app, I'd recommend creating a wrapper component for this:

```jsx
import { NavItem } from 'rebass'
import { Link } from 'react-router'

const MyNavItem = (props) => (
  <NavItem
    {...props}
    Component={Link} />
)

export default MyNavItem
```

Then you'd use it like this:
```jsx
<MyNavItem to='/' children='Home' />
```

**Comment by keithn** [comment]
Since I have hit this problem a couple of times now because it's a been a while between projects...   and this page seems the top hit in google when I search for it...

Component doesn't work, you need to use "is"  ( I think there is another issue explaining this, but can't find it at the moment )

```
<NavItem
      to='/'
      is={Link}
      children='Home' />
```

**Comment by R0bson** [comment]
Some point from me. Don't be too clever ;)

Below code WILL NOT work.
```
import { Button } from 'rebass'
const LinkButton = styled(Button).attrs({
  is: Link,
})`
  text-decoration: none;
`
```

React complains about calling component directly and styled-components crashes.
Solution to this is similar to above:
```
import { Button } from 'rebass'
const StyledButton = styled(Button)`
  text-decoration: none;
`

function LinkButton(props) {
  return <StyledButton {...props} is={Link} />
}

```

**Comment by detikpw** [comment]
Because googling and still get top for this issue, use `as` instead of `is`

```js
import { Link as RouterLink } from 'react-router'
import { Link as RebassLink } from 'rebass'

export default props =>
  <RebassLink
    {...props}
    as={RouterLink}
  />
```


https://github.com/rebassjs/rebass/issues/468
https://github.com/rebassjs/rebass/issues/539
https://www.styled-components.com/docs/api#as-polymorphic-prop
