### ISSUE TITLE
Add hide property to all components

### ISSUE THREAD

**Issue by romainquellec** [jxnblk/rebass#361]
In examples, we can find Hide from 'hidden-styled'.

I think we should add a property to all components like this instead of using hidden styled : 
`<Box hide=[xs, md]>`

What do you think ?

**Comment by jxnblk** [comment]
I think using `display: none` is something that should be used sparingly, and there's already the [`hidden`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) attribute which might be useful. And, in React you can return `false` to skip rendering, which is often a better solution 

Having a single purpose `Hide` component helps make this more explicit without adding complexity to default components
