### ISSUE TITLE
Make organization / Adding outside collaborators

### ISSUE THREAD

**Issue by romainquellec** [jxnblk/rebass#362]
Hi !
I think it's time for this project ans projects related ( styled-system, grid-styled, ...) to have more maintainers and collaborators. Maybe, we should get an organization around these ?

(I tried this on Twitter, maybe it will work better on GH)

@jxnblk

**Comment by lowsky** [comment]
Hi, I came across this great project and found that it seems to be stalled somehow and there was not much going on, even an upgrade on React 16 has been prepared, but was not merged.

@jxnblk Brent, can we as a community help to make this library stay "live and healthy" ? 

I would like you to allow more people to give assistance, so you could focus on eg. Lab, and all the other awesome stuff you create!

**Comment by DJTB** [comment]
It would be much appreciated. I spent a few days working on an app, then became blocked because I couldn't use innerRefs. It's a wonderful project - but allowing some community fixes if you don't have the time yourself would be very helpful to consumers of Rebass.

**Comment by jxnblk** [comment]
After the v2 release Rebass will probably move to an org, so closing this issue out for now
