### ISSUE TITLE
Make styled-components as external dependency

### ISSUE THREAD

**Issue by WangLarry** [jxnblk/rebass#363]
styled-components document say:
If you are a library author we recommend that you should not bundle styled-components module with your library. Instead, mark it as external dependency during your library build, move it from dependencies to devDependencies and include it in peerDependencies list in your package.json file:
```
  {
-   "dependencies" : {
+   "devDependencies" : {
      "styled-components": "^2.4.0"
    },
+   "peerDependencies" : {
+     "styled-components": "^2.4.0"
+   }
  }
```

**Comment by bessey** [comment]
Also, please loosen the dependency, if rebass works with 3.0+!
