### ISSUE TITLE
Anybody has a sample code for the carousel?

### ISSUE THREAD

**Issue by ferMartz** [jxnblk/rebass#368]
First of all, thanks to jxnblk and all the contributors to Rebass 🙌 .
You guys have done an excellent job with this framework!

With the help of this post:
http://jxnblk.com/writing/posts/patterns-for-style-composition-in-react/
I was able to create a carousel but I have not been able to use the native carousel of Rebass.
Anybody has a sample?

Thanks in advance 🙏

**Comment by jxnblk** [comment]
If you're using v2, see the example here: http://jxnblk.com/rebass/components/Carousel

**Comment by ferMartz** [comment]
Thanks @jxnblk (Brent). I made it work in v2!

One more question: Do you guys have a list of the new props for v2? Or what is the best way to find the correct props for each UI component? I noticed they changed. First, I checked the docs and I found few of them. Next I thought I could use styled-systems but only some work, correct me If I'm wrong!
The next thing I did was to check the component in the source code to see props. But, for example, caps for Text doesn't work anymore. I saw you have a new component Caps.js but I'm a bit confused because if I add caps to Text or any other typography  UI comp it just doesn't work.

Thanks again Brent...I'm a fan of your work here!

FM
