### ISSUE TITLE
Subhead.extend is not a function

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/rebass#369]
I don't know why but looks that is not possible use extend with `Subhead` 🤔

**Comment by jxnblk** [comment]
Thanks! Looks like it's not a styled-component, so that won't work. I'd recommend using the `styled(Subhead)` syntax since it sounds like `.extend` might be deprecated in the future – I should update the docs to reflect that though

**Comment by Kikobeats** [comment]
Yes, no problem I did that 🙂

Could be nice add `Subhead.extend` support just to expect the same API for all the component.

I don't know if in these case could be possible do something like:

```
Subhead.extend = styled.extend
```

**Comment by epilande** [comment]
Linking to the styled-component issue regarding deprecating `.extend` https://github.com/styled-components/styled-components/issues/1546

**Comment by jxnblk** [comment]
Yeah, I think the Subhead should be wrapped in a `styled()` function call to keep all the styled components properties and methods intact

**Comment by jxnblk** [comment]
Should be fixed now; please open a new issue if not
