### ISSUE TITLE
Missing arrow at Select component

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/rebass#371]
I'm updating my project from rebass 1.x and I note arrow is not present into select

<img width="1073" alt="screen shot 2018-03-07 at 22 43 00" src="https://user-images.githubusercontent.com/2096101/37120864-e0c0c770-225b-11e8-9df5-8f415db15304.png">

I suppose the inline svg as background-image is buggy

**Comment by jxnblk** [comment]
Yeah, that's definitely a bug with the 2.0 beta
