### ISSUE TITLE
IE11 Object.assign

### ISSUE THREAD

**Issue by pungggi** [jxnblk/rebass#379]
Hello 
In IE11 I get 

> Object doesn't support property or method 'assign'

I am using "rebass": "2.0.0-0"

Here is described how to polyfill>
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by jxnblk** [comment]
Thanks! I wouldn't want to add a polyfill, but using object spread syntax should work for wherever Object.assign has been used

**Comment by pungggi** [comment]
Ok can I do PR for that?

**Comment by jxnblk** [comment]
Sure, go for it!
