### ISSUE TITLE
Negative mx value with rem units

### ISSUE THREAD

**Issue by teddybradford** [jxnblk/rebass#381]
When I use a theme with `space: [0, "4rem", "8rem"]` and try to set a negative margin like in the grid example: `<Flex mx={-2}>`, the output is `margin-left: 8rem; margin-right: 8rem;` rather than `margin-left: -8rem; margin-right: -8rem;`

Is this intended?

**Comment by jxnblk** [comment]
As of now, string values aren't converted to numbers and thus can't be made negative. There's a [PR open](https://github.com/jxnblk/styled-system/pull/159) to allow this to work, but it's not been merged yet

**Comment by jxnblk** [comment]
This should be possible now since the above mentioned PR has been published
