### ISSUE TITLE
complexStyle

### ISSUE THREAD

**Issue by pungggi** [jxnblk/rebass#382]
I do not see any implementations of [complexStyle](https://github.com/jxnblk/styled-system/blob/master/README.md#complexstyle)
I find this very powerfull addition to rebass. Maybe 3,4  Styles as default..

**Comment by pungggi** [comment]
My suggestion is to have for each Component a complexStyle: 

for example: 
Card => cardStyles
Arrow => arrowStyles
Heading => headingStyles

and so on? What do you think?

**Comment by jxnblk** [comment]
The complexStyle function will likely be used for Button, Text, and Heading components, but still working out the props API to introduce for those

**Comment by jxnblk** [comment]
Closing this out, since this is planned for later
