### ISSUE TITLE
[Help] Props of Banner component

### ISSUE THREAD

**Issue by rdricco** [jxnblk/rebass#383]
How can I change the size of banner component? I've tried using styled-components but has no effect.

**Comment by jxnblk** [comment]
What do you mean by *size*? It has a `minHeight` prop as well as padding props, see https://github.com/jxnblk/rebass/blob/master/src/Banner.js

**Comment by rdricco** [comment]
I was trying to change the height but is not working. I got this messagem on console:

```
Warning: React does not recognize the `minHeight` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `minheight` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

```

I'm using rebass on gatsbyjs.
