### ISSUE TITLE
Creation of custom styled components

### ISSUE THREAD

**Issue by tpkiddle** [jxnblk/rebass#384]
Is there currently a way of creating custom components? Ideally through the use of styled-components 'styled' function?

**Comment by jxnblk** [comment]
Not sure I understand the question. You can use styled-components directly to create whatever components you want

**Comment by jxnblk** [comment]
You'll want to make sure you only install one instance of styled-components that's compatible with the range here https://github.com/jxnblk/rebass/blob/master/package.json#L29 – it might be worth `rm -rf node_modules && npm i` to see if that clears up your issue
