### ISSUE TITLE
_rebass.Blockquote.extend is not a function

### ISSUE THREAD

**Issue by sabrinaluo** [jxnblk/rebass#387]
Got above error while trying to extend the `Blockquote` components.

Currently I resolve this issue through `styled(Blockquote)`, but still hope there is a `.extend` method for each of the rebass component, which make a consistent experience.

**Comment by jxnblk** [comment]
Thanks! I'll need to do a pass to ensure all the components are wrapped with the styled-components HOC, but generally I'd recommend using the `styled(Blockquote)` syntax since `.extend` might be deprecated in a future release of styled-components

**Comment by macklinu** [comment]
Would you welcome a PR to update the **Extending** document to prefer `styled(Component)` over `Component.extend`?

![image](https://user-images.githubusercontent.com/2344137/39077798-4b7dc354-44b9-11e8-85f1-0c53bda33977.png)

**Comment by jxnblk** [comment]
A PR to update the `.extend` syntax in the docs would be welcome, but closing this issue out for now since the `.extend` method *should* work in Blockquote now
