### ISSUE TITLE
`colors` theme key should deep merge

### ISSUE THREAD

**Issue by brandonmp** [jxnblk/rebass#388]
atm the `Provider` just [merges the custom theme with the default](https://github.com/jxnblk/rebass/blob/master/src/Provider.js#L14), but with keys like `color`, the default adds some stuff that would be hard to recreate (eg `darken`).

should the `colors` key be deep merged so that `default` keys not in the custom theme are intact?

i noticed this b/c when I upgraded to `2.0`, buttons' hover effects disappeared (b/c my `colors` obj had no `darken` key)

**Comment by jxnblk** [comment]
I think rather than deep merging (which could potentially result in confusing behavior), it'd be better to handle the default colors in a more generic way and maybe remove the default pseudoclass styles from components like Button. I think it'd be way better for consumers to customize that however they need rather than inherit some opinionated defaults

**Comment by brandonmp** [comment]
> which could potentially result in confusing behavior

Can you elaborate here? my initial thought here is that merging user-provided props with default props is such a common pattern in `React` that I think users would find it pretty intuitive.

> it'd be better to handle the default colors in a more generic way and maybe remove the default pseudoclass styles from components like Button.

Of course I trust your judgment wrt what's best for the lib, but this sounds like a much bigger undertaking than simply adding an `Object.assign()` to the theme. Are there other benefits to a more substantial overhaul? 

> ...rather than inherit some opinionated defaults
I can't speak for others, but inheriting opinionated defaults is the reason I use libraries like Rebass in the first place, so I don't view this as a downside _provided overrides are available and intuitive_ (which I think deep merging the theme object is).

**Comment by jxnblk** [comment]
Replacing one object with another should not deep merge by default. If you'd like to merge the colors, I'd recommend importing the Rebass theme in your own theme and handling the merge there
