### ISSUE TITLE
No more online examples?

### ISSUE THREAD

**Issue by adavia** [jxnblk/rebass#398]
Are you guys doing some updates on the webpage? i cant see the component examples.
Thanks

**Comment by jxnblk** [comment]
Hi, making some updates to the docs. In the meantime, see:
- http://jxnblk.com/rebass/library/
- [component props reference](https://github.com/jxnblk/rebass/blob/master/docs/components.md)

**Comment by DarrylD** [comment]
Will that grid of components be the new design direction?

**Comment by elatezet** [comment]
Seems like not working anymore, http://jxnblk.com/rebass/library/ broken?

**Comment by dwalker11** [comment]
🙌 Online examples are back. Thank you! 🙌

**Comment by mattdiamond** [comment]
Yeah, I'm seeing ReferenceErrors all over the docs.

**Comment by schleumer** [comment]
Doc is dead for me too, had to clone the repo, checkout at v2.0.0-10 and compile doc D:

**Comment by jxnblk** [comment]
Docs should be working again. I'm closing this issue, but please open a new one if there are any other issues with the docs
