### ISSUE TITLE
Received `true` for a non-boolean attribute

### ISSUE THREAD

**Issue by kevin-wolf** [jxnblk/rebass#402]
I am trying to extend `<Text />` component in order to make it receive a `bold` prop. But apparently the prop is being written to the DOM

```jsx
import { Text as TextBase } from 'rebass';

const Text = TextBase.extend`
  font-weight: ${props => (props.bold ? "bold" : "normal")};
`;

;<Text bold>Hello I am bold!</Text>
```

<img width="594" alt="screen shot 2018-06-10 at 5 17 31 pm" src="https://user-images.githubusercontent.com/3157426/41207377-3697374a-6cd2-11e8-9b79-cf7c3e0c396e.png">

Any clean solution or suggestion to avoid this issue?

**Comment by jxnblk** [comment]
This is an issue with styled-components and how it passes props down to the element. For the Text component, using the `fontWeight` prop instead of a custom one should avoid this issue
