### ISSUE TITLE
Client side use

### ISSUE THREAD

**Issue by garyrob** [jxnblk/rebass#41]
Seems clear how to use rebass in the node environment, but I'd like it made clearer how to use it on the client side.

**Comment by jxnblk** [comment]
I'm not sure I understand your question, but It should work the same on both server and client – that's how React works. The demo folder has an example that uses client-side JS only.

**Comment by garyrob** [comment]
Maybe I'm totally missing something because of my relative inexperience, but your instructions show installing it into the node environment with npm, and then just importing it in javascript... but on the client side I'd assume you have to use <script src=<something>> instead... It would have been easier for me to understand if I'd seen that kind of example. Because I don't think the nom stuff helps client-side?

**Comment by jxnblk** [comment]
Oh, I think I get where you're coming from now. Libraries like React require something like webpack or browserify to bundle modules for client-side use. I'd recommend checking out webpack: http://webpack.github.io – it's a little bit cryptic at first, but well worth the effort. This is also a very good starting point for webpack: https://github.com/petehunt/webpack-howto

And, definitely check out what's happening in the demo folder. It's not really indicative of how you'd structure a real application, but it uses some similar tooling to create the `bundle.js` file.

**Comment by garyrob** [comment]
OK, thanks for the pointer, I appreciate it! Seems like your documentation would be clearer for folks like me who are just starting out if you added something about that, but maybe it does make sense to assume your users already know.

**Comment by jxnblk** [comment]
Yes, I would like to add more documentation, but was trying to get the basic functionality together first. Feel free to ask more questions if you get stuck anywhere along the way 😎
