### ISSUE TITLE
Colors Theme

### ISSUE THREAD

**Issue by felipeleusin** [jxnblk/rebass#425]
Hi,

I just had very good experience with rebass lately but one pain point is the colors. I come from an Android background so I might be biased and I realized this might be a little bit of an overkill to have at something like rebass but I reallylike https://material.io/design/color/the-color-system.html#color-theme-creation

When I used rebass I had some problem replacing the colors because in some cases such as ButtonOutline I had no way to change the hover color without extending the button. Because I can't change the color of the hover property or without having to do something like:
```
colors.blue = 'red'
```
that seems clunky.

Would you folks be open to change some of the colors so we can use something like primary / text ? I'd be willing to send a PR for this

**Comment by 18thletter** [comment]
For `ButtonOutline`, you can pass the `hover` prop to it, like this

```javascript
<ButtonOutline
  color='white'
  hover={{
    color: 'black',
    backgroundColor: 'white'
  }}
>
```

There should be a change to the docs: https://jxnblk.com/rebass/components/ButtonOutline. If you notice the `hover` property is `[object Object]`. But, it's clear in the source: https://github.com/jxnblk/rebass/blob/master/src/ButtonOutline.js#L9.

I'll make a PR for the doc thing when I can figure out why Jest seems to stall forever when running the test suite...

**Comment by jxnblk** [comment]
Thanks for the question. I'll be changing how the theming and colors work in the next major version, but probably won't address this in v2, hopefully the new version will be a little more flexible for what you're describing

**Comment by mikhailrojo** [comment]
Hi everyone
is here a way to use material design themes with rebassjs? the like 'plug-and-go'?
