### ISSUE TITLE
Tooltip triangle misplaced

### ISSUE THREAD

**Issue by salpulse** [jxnblk/rebass#426]
I'm using <Tooltip/>. It works fine in most places:
![image](https://user-images.githubusercontent.com/37205492/41939290-a2b1bf6e-79d8-11e8-8cbe-944db1ea9cc4.png)

But for one of my tooltips, the anchoring triangle is misplaced:
![image](https://user-images.githubusercontent.com/37205492/41939299-a9e286f6-79d8-11e8-846e-84bd2ec7d4e0.png)

Is this something to do with the style of the containing div?

**Comment by jxnblk** [comment]
Could be, but hard to tell. Do you have an isolated test case that you could maybe provide a Code Sandbox link to?

**Comment by salpulse** [comment]
I've switched to another tooltip library
