### ISSUE TITLE
Modal has page elements over the top

### ISSUE THREAD

**Issue by salpulse** [jxnblk/rebass#427]
I'm using Modal, but in one instance, (some) page elements are showing through the modal. It's like the z-index is not correct:
![image](https://user-images.githubusercontent.com/37205492/41943064-567d4174-79e5-11e8-9ca9-d03bf35994ca.png)

**Comment by jxnblk** [comment]
You can either set the `zIndex` prop on the component itself or control the stacking context with Relative components
