### ISSUE TITLE
Default color to primary instead of blue?

### ISSUE THREAD

**Issue by IniZio** [jxnblk/rebass#428]
Currently rebass components like button use `blue` as the default bg color and font color. Which is might be less convenient to theme.

Would making it to default to `primary` make it easier to override?

**Comment by jxnblk** [comment]
If blue isn't the primary color for your buttons, you can always extend the Button component and set the default `bg` prop to `green` or whatever you like (even `primary` if you want to alias it). Rebass tries not to be too opinionated about naming conventions to keep it (hopefully) more flexible for different use cases

**Comment by IniZio** [comment]
Yes it is very convenient to override each element, but for example I want the whole theme to be green, I will need to override one by one, since it does not really make sense to set 'blue' to a green hex :thinking: .

Instead using names like 'primary', 'secondary', 'danger' might make it more convenient, since I can just set it in Provider :smile:

**Comment by jxnblk** [comment]
For v2, the color keys are going to stay the same to prevent any breaking changes. The next major version of Rebass will hopefully be a lot more flexible in regards to colors and theming
