### ISSUE TITLE
Cannot find module '.'

### ISSUE THREAD

**Issue by andrewho83** [jxnblk/rebass#43]
This happens on Node 0.12.7 + Babel 6
Seems to be resolved after switching to Node 5.7

I think it has to do with the way things are exported in index.js

`
var _ = require('.');
`

**Comment by andrewho83** [comment]
Tried to use Rebass@0.1.5 with Node@0.12.7, and it works

**Comment by jxnblk** [comment]
I haven't tested in Node ~0.12, but I'd guess it might be this line: https://github.com/jxnblk/rebass/blob/master/src/index.js#L63

Does the older version of Node not support the full `import` syntax?

**Comment by andrewho83** [comment]
It gets compiled from babel, but I think the result still doesn't work properly.  

It's most likely an issue with Babel/Node

**Comment by SachaG** [comment]
I'm running into the same issue with Node 0.10.36 (in a Meteor app). Is there any way that line could be changed to be backwards compatible?

**Comment by SachaG** [comment]
(I can confirm version `0.1.5` works for me as well)
