### ISSUE TITLE
On v2, `Text` component is a `div`

### ISSUE THREAD

**Issue by luftywiranda13** [jxnblk/rebass#433]
![screen shot 2018-07-01 at 01 41 48](https://user-images.githubusercontent.com/22868432/42128832-b682755c-7cde-11e8-9e3f-3f7a2543fea3.png)

It should be a `paragraph`, ain't it?

**Comment by jxnblk** [comment]
You can set the HTML element with the `is` prop where appropriate, e.g. `<Text is='p' />`

**Comment by luftywiranda13** [comment]
yes I know we can set it with `is` prop.
But isn't it better to set `Text` as `p` element by default? Like what we have on v1?

**Comment by kripod** [comment]
@jxnblk What are the motivations behind making blocks of text a `div` by default? I think that using `p` for text is more frequent. Using `<Text is="div" />` would still be possible.

**Comment by jxnblk** [comment]
Not all text on a page is a paragraph, so overusing the `<p>` tag can also not be great. The Text component can also be used as a wrapping component around other semantic elements, where you could have something like

```jsx
<Text fontSize={3}>
  <p>...</p>
  <p>...</p>
  <ul>...</ul>
</Text>
```
