### ISSUE TITLE
Better classnames for development mode

### ISSUE THREAD

**Issue by MartinDawson** [jxnblk/rebass#434]
At the moment the classnames are mangled into base64 hash or something: 

e.g.

```js
class="sc-jAaTju kAxljF sc-bdVaJa iHZvIS"
```

It would be nice to somehow allow rebass to pass the folder_file_componentName:base64 for development mode. The same as how css-loader does it.

**Comment by johnmcdowall** [comment]
This isn't something `rebass` has control over, it's the responsibility of the underlying styling library being used, be it either `styled-components` or `emotion`. 

Both of those projects have options you can configure to enable contextual CSS class names. For emotion you would add the babel plugin and enable the `autoLabel` flag: https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion

**Comment by MartinDawson** [comment]
@johnmcdowall `babel-plugin-styled-components` seems to work for `styled-components` but not rebass components. Is their anything for rebass as well?

**Comment by johnmcdowall** [comment]
@MartinDawson Ah, I'm not sure about how to get the built in Rebass components to have their DisplayNames used as classes. Again though, pretty sure this isn't anything to do with Rebass, but styled-components. You might want to ask over there as well.

**Comment by probablyup** [comment]
@johnmcdowall if you transpile via babel, add the `babel-plugin-styled-components` plugin to your list

Otherwise, this can be achieved by the end developer via "including" rebass in your babel-loader regex or whatnot in conjunction with `babel-plugin-styled-components`.

**Comment by johnmcdowall** [comment]
@probablyup I'm not sure I follow - wouldn't `rebass` already be available to `babel-loader` by virtue of being in `node_modules`?

**Comment by probablyup** [comment]
@johnmcdowall the recommended config for babel-loader is to entirely exclude node_modules, so probably not for most projects.

**Comment by johnmcdowall** [comment]
@probablyup Ah, right yes - total brainfart moment. FWIW I am using `emotion` with `rebass` and adding it didn't do anything for me (more than likely because `emotion`'s `autoLabel` works differently than `styled-components), but maybe your solution will help @MartinDawson.

**Comment by jxnblk** [comment]
Hopefully the next major version of Rebass works a little better with CSS-in-JS library tooling, but there's probably not much I can do to accommodate this in the current version, so closing this out

**Comment by baddox** [comment]
Has there been any movement on this? I'm on the newest versions of Rebass and Emotion, and I have not been able to crack this. `autoLabel` is working fine when I `import { css } from '@emotion/core'` manually, but none of the styles that go through Rebass get anything added to their CSS classes.

It seems that `babel-plugin-emotion` and its configuration just isn't affecting Rebass component CSS classes at all.

I attempted including `node_modules/rebass` in my `babel-loader` rule, but that seems to have no effect.

<img width="276" alt="enterprise 2020-03-30 14-46-26" src="https://user-images.githubusercontent.com/307393/77965201-62b5da00-7295-11ea-93a6-4da1d517e961.png">

**Comment by clarkkozak** [comment]
@baddox I'm interesting to see if I can help out with this. Do you have any code to share for others to take a look?

**Comment by baddox** [comment]
@clarkkozak Thanks for reaching out! Here's a fairly minimal example with a fresh ejected create-react-app: https://github.com/baddox/rebass-emotion-autolabel

Here's the important commit: https://github.com/baddox/rebass-emotion-autolabel/commit/0fbfc9181970cdb98bfae9ace855fd1757cb43d8

When you `npm run start` you can see:
- The section which uses Emotion's `css` prop gets the CSS classes with my autoLabel configuration.
- But the section which uses Rebass components and style props gets the default Emotion CSS classes.

![DevTools - localhost:3000: 2020-03-31 11-44-45](https://user-images.githubusercontent.com/307393/78063496-2c379800-7345-11ea-9bbc-616768760c87.png)

Let me know if there's something else I can provide. Hopefully I'm just missing something silly!

**Comment by clarkkozak** [comment]
@baddox I believe your code demonstrates what is the desired output and what is the immediate issue. Well done!

Seems like this has been mentioned to the emotion team as well:

https://github.com/emotion-js/emotion/issues/756

The issue above suggests a way to create a solid headstart on where a PR could be made to make sure that the `autoLabel` feature can work for rebass components. Due to the nature of abstracting components, it may be quite the undertaking. 

Maybe even a fork of `babel-plugin-emotion` to `babel-plugin-rebass`? I'm unsure. I'm still learning this system. I'm here because wanted to see how good code is maintained, and perhaps I could help

@jxnblk and anyone else; please correct me if I'm wrong about anything.
