### ISSUE TITLE
Mobile responsive property visibility

### ISSUE THREAD

**Issue by kumark86** [jxnblk/rebass#436]
Is there any property available for show and hide depends upon the screen sizes like mobile and desktop browsers?

ex: I have menu bar in desktop browser. Instead of  display the menu bar I want to display drawer menu in mobile devices.

**Comment by jxnblk** [comment]
There is this component https://github.com/jxnblk/hidden-styled – I'd recommend either rolling your own or adding in some CSS where you need it

**Comment by BrendanFDMoore** [comment]
@jxnblk How does `Hide` from `hidden-styled` differ from `Hide` in `rebass`? 
http://jxnblk.com/rebass/components/Hide

I'm having some trouble with this in both cases, but in very different ways.

Using the `rebass` variant, showing the Modal with a Hide causes a UI crash: `Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Using the `hidden-styled` variant, I get highly unexpected results with the CSS affecting unrelated elements (I can open an issue over there, if you like.)

**Comment by BrendanFDMoore** [comment]
Hmm it looks like `Hide` in `rebass` is simply not exported as expected from the docs:

```
import { Hide } from 'rebass';
console.log('Hide component:', Hide);
// -> Hide component: undefined
```
