### ISSUE TITLE
NavLink <a>

### ISSUE THREAD

**Issue by jamalabo1** [jxnblk/rebass#438]
### modification request

in [NavLink](http://jxnblk.com/rebass/components/NavLink/) it automaticlly render <a> with href props
but i want to use <Link> (react-router-dom) and when do that an error popup (cant use nested dom);
(when use <NavLink> it use <a>) 

### the request is
add prop enableHref and can be set to false and the NavLink will be rendered as <span>

or just change href so i can use `{<Link to='/'>Home</Link>}`

**Comment by jxnblk** [comment]
For react router, use the is prop, `<RebassNavLink is={RouterNavLink} to=‘/‘ />`

**Comment by jamalabo1** [comment]
ok thanks 👍  :)
