### ISSUE TITLE
Add support for default margin/padding values

### ISSUE THREAD

**Issue by kripod** [jxnblk/rebass#442]
I think it would be great for some components (e.g. `Text` and `Heading`) to have support for default margin/padding props specified inside a `Provider`.

Also, if any kind of default props could be specified, then #433 could be eliminated with a syntax like the following:

```jsx
<Provider
  theme={{
    defaultProps: {
      Text: {
        is: 'p',
        my: 2,
      },
    },
  }}>
  <Text>
    I'm a paragraph.
  </Text>
</Provider>
```

**Comment by corygibbons** [comment]
You're better off doing this by extending the base `Text` component:

```js
import { Text } from 'rebass'

export default props => <Text is="p" my="2" {...props} />
```

**Comment by kripod** [comment]
Thanks for the tip!
