### ISSUE TITLE
Add support for typographic scales

### ISSUE THREAD

**Issue by kripod** [jxnblk/rebass#443]
I noticed that [the `Heading` component exports properties for all the different HTML heading types](https://github.com/jxnblk/rebass/blob/9c2bb7d049fe3d0023f31076e8cf5e41e3791b7e/src/Heading.js#L18-L23). Inspired by [typography.js](https://kyleamathews.github.io/typography.js/), I think it would be a great opportunity to be able to follow a [typographic scale](http://spencermortensen.com/articles/typographic-scale/) customizable through the `Provider` component.

**Comment by jxnblk** [comment]
You can set default props by extending the component, which is a more component-based approach imo:

```
const Title = props =>
  <Heading
    fontSize={6}
    {...props}
  />
```

**Comment by jxnblk** [comment]
Also, you can define the typographic scale by providing your own theme with a `fontSizes` array

**Comment by kripod** [comment]
Sounds great, I wasn't aware of the approach outlined above. Thank you!
