### ISSUE TITLE
Add BreakpointsConsumer component

### ISSUE THREAD

**Issue by kripod** [jxnblk/rebass#444]
Sometimes, it would be nice to know which breakpoint is being active. For instance, [optimizing for large-scale displays](https://css-tricks.com/optimizing-large-scale-displays/) requires the base font size to be adjusted as the viewport size changes.

I would like to propose a `BreakpointsConsumer` component which would expose the index of the currently active breakpoint (defined in `Provider`).

The following syntax could be used, showing how to [dynamically specify the number of columns for react-photo-gallery](http://neptunian.github.io/react-photo-gallery/examples/dynamic-columns.html):

```jsx
<BreakpointsConsumer>
  {(breakpointIndex) =>
    <Gallery
      columns={({
        0: 1,
        1: 2,
      }[breakpointIndex]) || 4}
    />
  }
</BreakpointsConsumer>
```

**Comment by jxnblk** [comment]
Thanks for the suggestion. This would probably be great as a separate standalone component for use with styled-components and emotion. I'd encourage you to consider making a package for this functionality if you're interested
