### ISSUE TITLE
Introduce shorthand properties

### ISSUE THREAD

**Issue by pke** [jxnblk/rebass#45]
I really like the minimalist approach of this lib after ditching `material-ui`.

I have a proposal to make the components even more easier to read:

Given the current state

```
<Flex
  align="center"
  justify="space-between"
  wrap={true}
>
```

What do you think about:

`<Flex center space-between wrap>`

Would that make sense?

**Comment by pke** [comment]
A sorry, mixed up the projects. That should go to http://jxnblk.com/reflexbox/

**Comment by phated** [comment]
Btw, that already works. It's how jsx gets translated.

**Comment by jxnblk** [comment]
Yeah I use shorthand booleans where appropriate (e.g. wrap). The docs are automatically generated from parsing jsx and it adds the true to props.

I tend to avoid booleans for potentially conflicting props like align and justify since they both have multiple possible values.
