### ISSUE TITLE
Width always 100% for Select

### ISSUE THREAD

**Issue by dardub** [jxnblk/rebass#450]
No matter what value I give to width prop for select, it always adds 100% width.

I see in Select.js a width value is given twice. Is this intentional?

https://github.com/jxnblk/rebass/blob/717f0968b69d9ba9bc339cb737269373e243303d/src/Select.js#L24

**Comment by dardub** [comment]
I'm finding other props don't work as expected or it does not match up with the documentation. I'm using emotion in case that is part of the problem.

I'm new to Rebass, so I wanted to get clarification if this is user error. Otherwise I can make a PR.

**Comment by jxnblk** [comment]
Should be fixed in `v2.3.0`
