### ISSUE TITLE
Add mdx example

### ISSUE THREAD

**Issue by Kikobeats** [jxnblk/rebass#451]
I noted that MDX adapter is present in the repository:
https://github.com/jxnblk/rebass/tree/master/mdx

Need to add an example for unlocking this awesome approach for write markdown into React component ✨

**Comment by jxnblk** [comment]
Sorry for the delay, I've moved that package to a new repo, if you wanna open an issue there https://github.com/rebassjs/mdx – hopefully the minimal README is enough to go off of to get started
