### ISSUE TITLE
No borderRadius in Box component

### ISSUE THREAD

**Issue by sarneeh** [jxnblk/rebass#452]
If I understand it properly, `rebass` is based on `styled-system`, which has in its API a `borderRadius` property for the `Box` element. 

My question is why the property is unavailable in `rebass`? It would be very helpful 😄

**Comment by sarneeh** [comment]
@jxnblk Thanks for the explanation! 👍

**Comment by grelas** [comment]
Would this be the right way to style specific border-radius props vs. just using the `borderRadius` prop?

```
<Image
     css={{
        borderTopLeftRadius: theme.radii[1],
        borderTopRightRadius: theme.radii[1]
      }}
/>
```
