### ISSUE TITLE
Unnecessary peerDependencies cause installation errors

### ISSUE THREAD

**Issue by mikl** [jxnblk/rebass#454]
Rebass now has peerDependencies for both styled-components *and* Emotion.

That means you now *have* to install both to avoid getting constantly yelled at by npm/yarn.

If you don’t have Emotion, this error is output by yarn:

```
warning "rebass > grid-styled@4.3.3" has unmet peer dependency "emotion@>=9.0".
warning "rebass > grid-styled@4.3.3" has unmet peer dependency "react-emotion@>=9.0".
```

And if you don’t have styled-components, this is the error message:

```
warning "rebass > grid-styled@4.3.3" has unmet peer dependency "styled-components@>=2.0 || >=3.0".
warning " > rebass@2.0.0-10" has unmet peer dependency "styled-components@>=2.0 || >= 3.0".
```
The easiest fix for this would be to simply remove the peerDependencies, since there’s no reason to need both installed. You could also make separate rebass-emotion and rebass-styled-components that could peerDepend on their respecitive style backends.

**Comment by jxnblk** [comment]
Should be fixed in `v2.3.0`
