### ISSUE TITLE
fontFamily prop not working

### ISSUE THREAD

**Issue by mattrothenberg** [jxnblk/rebass#456]
Howdy! First and foremost, thanks for building + maintaining this project. 

I'm trying to use the `fontFamily` prop on a `<Text>` component, as per the example in the docs. 

https://jxnblk.com/rebass/components/Text
```jsx
<Text
  textAlign='center'
  fontWeight='bold'
  fontFamily="serif"
  children='Hello'
/>
```

However, on both my local project + the following Codesandbox, I can't seem to get the `fontFamily` prop to actually change the style of the `<Text/>`. It just converts the property into a kebab case HTML attribute. https://codesandbox.io/s/0vryoo593p

What am I doing wrong? Thanks!

**Comment by jxnblk** [comment]
Looks like Rebass is installed with the `next` tag in codesandbox, can you try installing the latest instead and see if the issue persists?

**Comment by mattrothenberg** [comment]
@jxnblk That did the trick. D'oh.

Thank you!
