### ISSUE TITLE
Feature Request, text-transform

### ISSUE THREAD

**Issue by alex-wilmer** [jxnblk/rebass#460]
Uppercase and lowercase are pretty common Text attributes.

 ```
<Text tt="uppercase" />
```

thoughts?

thanks, and great lib

**Comment by jxnblk** [comment]
There is a Caps component for uppercase, I think for lowercase you should create your own components

**Comment by alex-wilmer** [comment]
Thanks :)

**Comment by alex-wilmer** [comment]
It's a little annoying to have to swap the component if I need to toggle, but I guess that's a pretty rare case.

**Comment by alex-wilmer** [comment]
What about other text properties iike `letter-spacing`? Sorry don't mean to waste your time, just curious why these things aren't baked in.

**Comment by alex-wilmer** [comment]
sorry I meant, why is letterspacing on caps but not on text?

**Comment by jxnblk** [comment]
I tend not to change letterspacing on a per-component basis. Generally I think that's better to set as a default on a root component, but you can always extend Text to add that as a prop

```js
import styled from 'styled-components'
import { Text } from 'rebass'
import { letterSpacing } from 'styled-system'

const MyText = styled(Text)([], letterSpacing)
```
