### ISSUE TITLE
Allow custom defaults to be set for components.

### ISSUE THREAD

**Issue by jckw** [jxnblk/rebass#461]
Although there is the ability to use an objects as the value for a key in the theme, e.g. 

```
const theme = {
    fontSizes: {
        small: 12,
        large: 18
    }
}
```

However, this means that the default values (for `fontSize`, in this case) for each component, such as [Heading](https://github.com/jxnblk/rebass/blob/master/src/Heading.js#L6) will become a fixed amount of pixels as opposed to a reference to the theme. 

It would be useful to be able to set defaults for components so that it's not necessary to define `fontSize={'large'}` for `Heading`. 

This could be done by each user with a wrapper, but it seems like a feature that would be nicely bundled with Rebass - unless there's already a way to do this, and I'm just missing it!

**Comment by jxnblk** [comment]
If you'd like to do this now, I'd recommend extending the core components where needed, e.g.

```jsx
const Heading = props =>
  <RebassHeading
    {...props}
    fontSize='large'
  />
```

But, yeah a wrapper function to make this config-based could be added as an optional package, I'm just hesitant to add more API surface area to the core library, if that makes sense

**Comment by jckw** [comment]
Yeah, I was considering doing this. It just adds a chunk of friction to prototyping/ messing around with Rebass since *every* component we use would need to have it's own wrapper component. Considering the size of Rebass (which is amazing) it's a real chore.

I understand that you don't want to have a huuuuge API, but this seems to be a pretty logical replacement for the hard-coded indices that are being used at the moment. Defaulting to showing 5px headers doesn't seem like the right response to a user changing some values in a perfectly valid way.

**Comment by jxnblk** [comment]
You can also keep the array for `fontSizes` in the theme and add the keys for convenience, we do that with breakpoints here: https://github.com/pricelinelabs/design-system/blob/master/src/theme.js#L3-L20

**Comment by jckw** [comment]
Would it not be sensible to make it easier to use keys rather than have to implement something like that just for convenience?

There doesn't seem to be a use-case for defaulting to array indices that turn up as pixel units whilst still using a key-based theme spec.
