### ISSUE TITLE
Setting padding does not override default horizontal and vertical padding. 

### ISSUE THREAD

**Issue by jckw** [jxnblk/rebass#463]
Take a `Button` with padding 5 (which maps to a value of `32px`):

```
<Button p={5}>Click here</Button>
```

The resulting CSS includes the custom padding **before** the defaults.

![image](https://user-images.githubusercontent.com/11884004/44453771-dab81a80-a5f1-11e8-8cb3-2cd2527a0eb2.png)

This is because `Button` has `px={3}` and `py={2}` set as a default, which are not overridden. 

Creating a button like this solves the problem:

```
<Button px={5} py={5}>Click here</Button>
```

The ideal functionality is to remove `px` and `py` if they're not specified when `p` is, but alternatively a quick fix would be to define the default values *before* the specified values when the CSS is generated.

**Comment by jxnblk** [comment]
The `p` prop is similar to the `padding` shorthand CSS property, so to override a normal property like `padding-top`, you'll need to specify `padding-top` – this is how styled-system's API is set up to work
