### ISSUE TITLE
Consider using `as` instead of `is`

### ISSUE THREAD

**Issue by kripod** [jxnblk/rebass#468]
According to the [v4 announcement blog post of styled-components](https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112), the `as` prop will be supported by any styled component.

It would be nice to keep the API consistent with the most popular CSS-in-JS library, so developers wouldn't have to use `as` and `is` interchangeably.

**Comment by jxnblk** [comment]
Going to close this out, but expect full support for the `as` prop in v3
