### ISSUE TITLE
Setting image placeholder in Rebass

### ISSUE THREAD

**Issue by areohbe** [jxnblk/rebass#470]
I currently have a rather not so elegant way to handle this within my app, but I am wondering if there is a cleaner approach within Rebass (or using some of the underlying libraries) to set a default placeholder for components like `image`, `avatar` or the `card` in the instance a value is not returned on the page. Thanks. 🙏

**Comment by jxnblk** [comment]
Maybe you figured this out, but sounds like you could set a default prop for `src`? Should work with any `<img>` element
