### ISSUE TITLE
Object.assign is not a function 😞

### ISSUE THREAD

**Issue by forresto** [jxnblk/rebass#50]
Chromium (37) and Firefox (31) on Travis are oldish and complain that `Object.assign is not a function`: https://travis-ci.org/the-grid/ed/builds/115555196#L962

I'll see if this polyfill helps: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

**Comment by forresto** [comment]
That fixed it. Would you put that polyfill in Rebass?

**Comment by jxnblk** [comment]
Doesn't babel have a polyfill for `Object.assign`? Would rather keep things in the Babel ecosystem if possible.

**Comment by jxnblk** [comment]
I think this is the one: https://babeljs.io/docs/usage/polyfill/

Either I can try to add it or you can submit a PR if you're already working on something :sunglasses:

**Comment by jxnblk** [comment]
On second thought, maybe this should just be a peer dependency...
**or** I should replace `Object.assign` with the spread syntax, which I think Babel handles better...

**Comment by phated** [comment]
Babel inlines an extend method if you use spread syntax in jsx (notice that it's already inserted in the output)

**Comment by forresto** [comment]
I just put the polyfill in my own project, but upstream fix would be appreciated.

**Comment by jxnblk** [comment]
Native `Object.assign` should be gone now in `0.2.4`. Let me know if it's still lingering around somewhere.
