### ISSUE TITLE
Default styles for complex components

### ISSUE THREAD

**Issue by austinsc** [jxnblk/rebass#51]
What is the best approach for setting a default style on complex components? In other words, how do I add a global style for the help text underneath an `<Input />` control?

**Comment by jxnblk** [comment]
For now, you can set global styles for `Text`, which is what the Input component uses for the helper text. I'm working on a way to target sub-component elements with something like `Input_helper`, `Input_label`, etc., but still trying to figure out the best way to approach that. If you're inclined to do so, you can also target the helper text with CSS (`.Input .Text`), but that breaks component encapsulation and might break in the future.
