### ISSUE TITLE
Stat "instance overrides" styling of value, unit, label

### ISSUE THREAD

**Issue by primozs** [jxnblk/rebass#54]
If I am not missing something currently "instance styling" of value, unit and label is not possible with `style` proptype? Change of proptypes `fontSize` `bold` and `scale` for example. 
Cheers

**Comment by jxnblk** [comment]
Thanks! I'm looking into a better way to configure the more complex components like this one, so stay tuned.

**Comment by primozs** [comment]
What about introducing new `sx` prop: 
```
  let sx = {
    root: {
      display: 'inline-block'
    },
    value: {
      fontSize: fontSizes[0],
      letterSpace: '-.125em',
      fontWeight: bold,
      lineHeight: 1,
      marginTop: topLabel ? scale[1] / 2 : null,
      marginBottom: topLabel ? null : scale[1] / 2
    },
    unit: {
      fontSize: fontSizes[3]
    },
    label: {
      fontSize: fontSizes[6],
      fontWeight: bold,
      lineHeight: 1
    }
  };

  sx = {
    ...sx,
    ...props.sx
  };
```

**Comment by jxnblk** [comment]
I think I'd rather just leverage the default `style` prop if possible. Is there any reason nesting objects for sub elements in `style` wouldn't work?

E.g.

```js
style = {
  color: 'tomato', // passed to the root element
  Stat_value: { // passed to sub elements by name
    color: 'green'
  }
}
```

**Comment by primozs** [comment]
This would be good... This is not implemented right?

**Comment by jxnblk** [comment]
Not currently, no
