### ISSUE TITLE
CHANGES.md

### ISSUE THREAD

**Issue by forresto** [jxnblk/rebass#56]
Is there a place to look to see changes?

**Comment by jxnblk** [comment]
Typically I use GitHub's releases for changes. For this repo, 0.2 was a complete rewrite, but I haven't taken the time to document the differences between the current and previous version.

I'm not opposed to starting a CHANGES.md though.

**Comment by forresto** [comment]
What's new in 0.2.5?

**Comment by forresto** [comment]
CHANGES.:trollface:
What's new in 0.2.6?

**Comment by forresto** [comment]
What's new in 0.3.0??? 😽
