### ISSUE TITLE
Advanced Components

### ISSUE THREAD

**Issue by jxnblk** [jxnblk/rebass#6]
- [ ] Navbar Collapse
- [ ] Collapse Trigger
- [ ] Tabs (disclosure mechanism)
- [ ] Modal Trigger
- [ ] Tooltip
- [ ] Popover

**Comment by jxnblk** [comment]
- [ ] SequenceMap (buttons and static items)

**Comment by jxnblk** [comment]
- [ ] toast

**Comment by jxnblk** [comment]
- Auto-abbreviating: date, time, number, etc

**Comment by jxnblk** [comment]
Marquee truncate

**Comment by iashris** [comment]
Will these features be implemented in the future?
