### ISSUE TITLE
make styles object accessible on each component

### ISSUE THREAD

**Issue by contra** [jxnblk/rebass#60]
it would be nice to be able to do this

``` js
import { Input } from 'rebass'

// blah blah
<CustomInput
  type='whatever'
  style={{
    ...Input.style,
    customThing: 123
  }}
/>
```

**Comment by phated** [comment]
Are you talking about default styling or the context stuff?  The context styling couldn't be exposed as a static property, as it is instance based.

**Comment by contra** [comment]
@phated Default styling

**Comment by jxnblk** [comment]
Why not just do something like this?

```jsx
import { Input } from 'rebass'

const CustomInput = (props) => (
  <Input {...props} style={whatever} />
)

export default CustomInput
```

**Comment by contra** [comment]
@jxnblk CustomInput in this case is a third party module (redux forms shit), not something I control. Also does not work with the `is` option.

Is there any reason to not expose this information?

**Comment by jxnblk** [comment]
Ah that makes sense, and I guess not. You'd lose all the Base component props but guess that doesn't matter in your case.
