### ISSUE TITLE
Rebass doesn't work with React 0.15

### ISSUE THREAD

**Issue by shalastra** [jxnblk/rebass#66]
```
npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer rebass@0.2.5 wants react@^0.14.0
```

I'm getting this error while I'm trying install rebass to my React project. Is there any chance to fix this?

**Comment by jxnblk** [comment]
It should still work (i.e. it was working for me over the weekend). npm just warns. 

#67 should fix this as soon as I publish an update.
