### ISSUE TITLE
What is a presentational component?

### ISSUE THREAD

**Issue by jagare** [jxnblk/rebass#69]
In the doc it reads
"Presentational components work with any application architecture"
and there is a reference to Dan Abramovs article on [Medium] (https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.wgnchqdx4).
However I think you refer to his initial definition of Presentational components, which he later changed, so that they can now include container components and then above statement is not true any longer.
I've tried to get attention to this since I think it is better to keep them "pure" [see] (https://medium.com/@lars.jagare/pure-components-ftw-63e6e6c733f0#.kp5vksebm).
Since the terminology / definition is now really confusing I propose you specify explicitly what you mean or ask Dan to revert back to his initial definition ;-)

**Comment by jxnblk** [comment]
Yes, I'm not sure I follow the whole *May contain both presentational and container components* part, and I would like to have better demos of how Rebass's UI components could be used in real applications, but I think generally the term still fits.
