### ISSUE TITLE
It appears Badge's text color can never be overwritten (possibly others?)

### ISSUE THREAD

**Issue by bentatum** [jxnblk/rebass#70]
https://github.com/jxnblk/rebass/blob/master/src/Badge.js#L24

Should Badge's text color ever need to change, it doesn't appear as though there's a nice way to override this. Is this by design? 

Maybe there is a good way to handle base/default text color that I'm missing?

**Comment by jxnblk** [comment]
That's somewhat true. I looked into using the [color](https://www.npmjs.com/package/color) package to pick a dark or light text color, but that felt heavy-handed. You can configure Badge's text color using context, but it will be the same value for all variations.

**Comment by bentatum** [comment]
thanks
