### ISSUE TITLE
[Question] Custom styling Component child Elements

### ISSUE THREAD

**Issue by jjordy** [jxnblk/rebass#71]
First off let me start by saying this library is fantastic. My question is as follows. Say i want to style the switch Component. in my config I have followed your demo config style by just passing in the config object. But if i just do something like
`Switch: {
    width: scale[2] * 1.5,
    height: scale[2] * 1.5
}`

It only styles the parent Container but not the dot.

I saw in your mono config where you did something like 

`Input: {
  input: {
    ...someStyles
  }
}`

But this isn't working for me either.

Im at a loss for how to handle this if you could let me know your reccommended approach for sub components that would be awesome. 

Thanks again man,

Jordy

**Comment by jxnblk** [comment]
Currently subcomponent styling through context doesn't work. What you've found in the mono demo is an indication of how I'd like the API for that to work. Ideally you should be able to configure something like:

```js
Switch: {
  dot: { height, width }
}
```

I'm still thinking about ways to handle this (as well as #57) so keep an eye out for updates.

**Comment by jjordy** [comment]
Sounds good man I def think that would be the ideal way to do it.
