### ISSUE TITLE
focusing inputs / input refs

### ISSUE THREAD

**Issue by contra** [jxnblk/rebass#72]
The standard way of focusing inputs doesn't work with rebass inputs. Typically you pass a ref function, like `ref={(e) => e.focus()}` but the ref gets a null value on rebass not the input element.

Two possible solutions:

- Make the ref on an Input component receive the input element, which might not be right since ref is supposed to be whatever the rendered element is. Would be non-standard if it didn't include the label and container as well.
- Add a `focused` attribute to the Input component that can be used to control if the element is focused or not

LMK what you think 🌴

**Comment by jxnblk** [comment]
Related to #68 - afaik the only good solution is to change form elements into class components or wait for react to support a solution for functional components. LMK if I'm missing something obvious though.

**Comment by justingreenberg** [comment]
maybe we could provide input components with a callback to binds the ref on initial render, maybe around ~ https://github.com/jxnblk/rebass/blob/master/src/Base.js#L29 with something like this....

```js
  // pass to `getRef` callback
  if (tagName === 'input' && typeof props.getRef === 'function') {
    props = assign(props, { ref: { c => c ? props.getRef(c) : x => x } })
  }
```

component (simplified mental model for demo....)
```js
// mock rebass input
const Input = ({ getRef, ...props }) => (
  <input { ...props } ref={ c => getRef(c) } />  //  ref provider in Base.js (above)
)
```

this makes usage super intuitive...
```js
  <Input
    getRef={ ref => ref.focus() } // works!
    onChange={ dispatchSomething } /> 
```
 @contra here's a little working jsfiddle to illustrate https://jsfiddle.net/69z2wepo/39603/

@jxnblk what do you think? let me know if you want a PR for `getRef` or similar :)

**Comment by theseyi** [comment]
@justingreenberg @jxnblk 
As per @justingreenberg 's solution above, why can't the prop name be ref rather than baseRef or am I missing something?
Also when can we expect a fix for this? Are there concerns?

**Comment by phated** [comment]
I don't think it's wise for this library to implement some solution for `ref`s outside of React.  The 2 solutions I see are making form elements class components (as originally suggested) or add a higher-order component that wraps the stateless component in a class component.

**Comment by justingreenberg** [comment]
@phated the proposed solution above just provides a hook for `ref` on the base component... 

>The 2 solutions I see are making form elements class components (as originally suggested) or add a higher-order component that wraps the stateless component in a class component.

can you provide some code or a demo? since all rebass components are wrapped in stateless function component (base hoc), afaik there is no other way to implement this functionality

**Comment by justingreenberg** [comment]
@theseyi renaming ref to `baseRef` prevents namespace conflicts and keeps the ref provider explicitly outside react's component api

**Comment by theseyi** [comment]
@justingreenberg Shouldn't it be that case that if the proposed solution is just a 'hook for `ref`' (which I'm interpreting as a proxy), then it should be the same name and just fall through to the react component?

**Comment by jxnblk** [comment]
This *should* work with `baseRef` now in v0.3.0

**Comment by geirman** [comment]
The `baseRef={ref => ref.focus()}` works, but I can't find this referenced anywhere in the documentation. Is there a better place to look than http://jxnblk.com/rebass/? If so, I'd love a pointer.

**Comment by jxnblk** [comment]
@geirman For using refs in ^1.0.0 see the styled-components' docs https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#refs-to-dom-nodes
