### ISSUE TITLE
Can't set hover from within react context

### ISSUE THREAD

**Issue by Tectract** [jxnblk/rebass#73]
I'm trying to customize this button element to do a background color change on a "hover". Can't figure out how to do it. Nothing I put into this getChildContext function seems to have the effect I'm looking for. Here's what I'm trying:

  getChildContext: ->
    rebass:
      Button:
        backgroundColor: 'blue'

      Button:hover:
        backgroundColor: 'green'

I don't really understand the last section in the README.md that mentions hover. Am I supposed to stick that somewhere in a separate .css file? I thought the whole point of rebass and JS CSS modules was that I wouldn't need to have special rules in CSS files anymore. (?)

**Comment by jxnblk** [comment]
The way things are implemented currently (and since there's no `:hover` state with inline styles), there's no way to set hover state with the configuration object. There are several ways to handle CSS within your own setup, but I think that using CSS for things like hover and focus states is the best way to go with the technology available right now. I'll try to clarify that better in the docs.

It's also worth noting that these are all stateless components, so it would require a higher-order container component to control hover state with mouse events.

**Comment by Tectract** [comment]
This really cripples Rebass, imho. I disagree that a JS CSS module should require a mixture of JS and CSS files, that is a really bad fragmentation and basically destroys my incentive to use Rebass at all.

**Comment by ddispaltro** [comment]
It's usually a tiny amount of code and a limitation with inline styles, since they are pseudo-selectors.  I consider it a big win when the only css you have is something like this:

```css
.Input input:focus {
  outline: none;
  box-shadow: 0 0 0 2px #00749d;
}
```

**Comment by Tectract** [comment]
Problem is that is breaks deterministic ordering and logical separation of code, which are the main two reasons I wanted to use JS CSS modules, as those are the two features that can't be handled properly when using .css files. I'm looking at switching to a different JS CSS module, or just writing my own now, that will not require the use of .css or .sass files.

**Comment by Tectract** [comment]
Hmmmm, I'm able to override the default styles using !important in a scss file, but I'm having a hard time setting those variables using contexts, can't seem to get any effect here, maybe because I'm using coffeescript and there is no "static" keywork possibly. I should just be able to stick a Button xml element into the render response right? Or is there some setting of state I need to do or something to get those Button variables to pass to the childContext or something? I looked at the demo code but the mechanism there is more complex. Here is an example very simple page, where I'm trying to set the backgroundColor of a button to green, but it's not working, maybe you can help me figure out why?
 # @cjsx React.DOM

 @View = React.createClass
   displayName: 'View'

   childContextTypes:
     rebass: React.PropTypes.object

   getChildContext: ->
     rebass: 
         Button:
            backgroundColor: 'green'

   render: -> 

     <div className='topLevelView'>
       <Button
         rounded={true}
         pill={true}
       >button</Button>
     </div>
