### ISSUE TITLE
blue border for button or input and so on

### ISSUE THREAD

**Issue by colinshen** [jxnblk/rebass#74]
I found that buttons or inputs on chrome have a blue border, I use edge to see the demo page again. there is no blue border for buttons.

**Comment by jxnblk** [comment]
Was this issue resolved? I haven't had a chance to test on Edge yet.

**Comment by colinshen** [comment]
I think it is the default focus style for some browsers. So, but I still think it is better to remove it.
```
.button: {
    outline: none
}
```

**Comment by jxnblk** [comment]
You should never remove outline without replacing it with another visual affordance.

**Comment by walleXD** [comment]
@jxnblk this issue still persists only in chrome. What's the best way to fix it?
