### ISSUE TITLE
Slider - thumb size configurability

### ISSUE THREAD

**Issue by bentatum** [jxnblk/rebass#75]
I have a branch here locally that adds a property to control thumb sizing on the `Slider` component. Would you be willing to allow me to submit a pull request?

**Comment by bentatum** [comment]
@jxnblk

**Comment by jxnblk** [comment]
Of course. I've been thinking about a way to handle subcomponent styles across the entire library. See #54

**Comment by bentatum** [comment]
@jxnblk awesome. Looks like I need to be approved to push a new branch & create submit a pr.

**Comment by jxnblk** [comment]
You can fork and submit a pr. Have you done that before?

**Comment by bentatum** [comment]
Ah, of-course! Will do.
