### ISSUE TITLE
Tooltip, double message

### ISSUE THREAD

**Issue by anton6** [jxnblk/rebass#79]
Getting double tooltip message when hovering over the element. (I used code example)

![tooltip](https://cloud.githubusercontent.com/assets/16119505/15397934/c4e0c024-1dd9-11e6-9fa2-7b56f6c26dd2.jpg)

Is anyone else getting this or just me?
I'm using rebass: 0.2.6

**Comment by jxnblk** [comment]
Can you post the code for this or a link to a jsbin?

**Comment by anton6** [comment]
It's just the code example. My colleague  pointed out, that it's because of title tag. https://github.com/jxnblk/rebass/blob/5f848c9e4afdfb21f3d528fddde137220b220905/src/Tooltip.js#L55

Not sure if that behaviour was intended, but maybe you can make it optional through props?

**Comment by lachlanjc** [comment]
Yep I noticed this as well — you get the browser's default tooltip (which doesn't look so similar on a Mac) through the `title` attribute, and then the one you asked for with Rebass. A good workaround to keep the tooltip accessible is to use the `aria-label` attribute. GitHub uses this in Primer: http://primercss.io/tooltips/ ([source code](https://github.com/primer/tooltips/blob/master/lib/tooltips.scss#L22))
