### ISSUE TITLE
How to scale components for use on mobile devices?

### ISSUE THREAD

**Issue by andrzey** [jxnblk/rebass#87]
Is there a way to customize elements so that they get resized to use on retina-devices? I am using MediaQueries to separate between mobile and desktop, is there a way to customize for example the Label-element on the Input-element without doing it globally?

**Comment by jxnblk** [comment]
If you're using CSS, you can target `.Input .Label` specifically. I'm not sure if that's what you're looking for...

**Comment by andrzey** [comment]
Is it possible to do this with inline-style by using the style-prop on the component?

Mvh Andre Thingstad

**Comment by jxnblk** [comment]
Inline styles do not support media queries. Your best bet for changing styles conditionally based on viewport is to use some custom CSS.
