### ISSUE TITLE
borderRadius cannot be overridden per component

### ISSUE THREAD

**Issue by SimeonC** [jxnblk/rebass#89]
I attempted to use the following code in the context:

```
rebass: {
    Button: {
        border: 'none',
        borderRadius: 16
    }
}
```

It seems that the `rebass.borderRadius` value cannot be overridden by any of the other themeing settings. Is this a bug or have I missed somewhere about how to do this?

**Comment by jxnblk** [comment]
This is somewhere between a bug and how it currently works. I think the desired behavior is for the borderRadius value in the config to actually work. Feel free to open a PR, otherwise I'll try to fix this in the next few patches.
