### ISSUE TITLE
Select - outer element is not rounded

### ISSUE THREAD

**Issue by bentatum** [jxnblk/rebass#90]
`Select` component with a `backgroundColor` demonstrates this well. See attached image.

Currently looks like this:
![screen shot 2016-06-09 at 3 33 56 pm](https://cloud.githubusercontent.com/assets/4211826/15944378/4c6bc106-2e5b-11e6-8e0b-64087b962899.png)

Should look like this:
![screen shot 2016-06-09 at 4 14 40 pm](https://cloud.githubusercontent.com/assets/4211826/15944814/4d8965f0-2e5d-11e6-91a6-2eb418f47642.png)

**Comment by jxnblk** [comment]
If you'd like to add a box style around form element components, I'd suggest using composition to create a visual wrapper.

e.g.
```js
<Box>
  <Select {...selectProps} />
</Box>
```
