### ISSUE TITLE
Can't override certain default props

### ISSUE THREAD

**Issue by andrewsuzuki** [jxnblk/rebass#94]
Take `Button` for example. It has the default prop `backgroundColor`, so if a prop is not supplied, `backgroundColor: 'primary'` trickles down to this.props, then into `Base`, where on the line 40 call to `colorStyle` it will override any `backgroundColor` within `contextStyle`.

Is this the intended behavior? I think this happens with any default prop that intersects with the utils margins, padding, colorStyle, or radii.

If not, I think repeating lines 39-42 of `Base` using `contextStyle` instead of `props` will fix it? I can submit a PR if so.

**Comment by jxnblk** [comment]
Thanks, I think this is part of a bigger issue (related #89).

Generally, I don't think any of the source components in Rebass should use the shortcut props like `backgroundColor`, and instead leave those available for end users. I *think* removing any of those default props would fix the issue you're describing here.

**Comment by eilijah69** [comment]
Maybe it should be temporarily removed (or annoted) from the readme example (line 86) until it is fixed.  It's pretty disturbing to discovering the projectwith a non working example. It's like you don't know if you forgot something somewhere.
