### ISSUE TITLE
NavItem with react router Link comes up with an error 

### ISSUE THREAD

**Issue by keithn** [jxnblk/rebass#98]
given

```
import React from 'react'
import { Link } from 'react-router';
import { Fixed,  NavItem,  Toolbar} from 'rebass'

const Navbar = () => (
  <Fixed top left right zIndex={1}>
    <Toolbar>
       <NavItem Component={Link} to='/'>Home</NavItem>       
    </Toolbar>
  </Fixed>
)

export default Navbar
```

I'm getting a browser error :-

app.js:2333 Warning: Unknown prop `Component` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by Base)
    in Base (created by NavItem)
    in NavItem (created by Navbar)
    in div (created by Base)
    in Base (created by Toolbar)
    in Toolbar (created by Navbar)
    in div (created by Base)
    in Base (created by Fixed)
    in Fixed (created by Navbar)
    in Navbar (created by App)
    in div (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

and it can't navigate.... 

if I do something like `<NavItem><Link to='/'>Home</Link></NavItem>`  it works but comes up with an error   app.js:2333 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See Navbar > NavItem > Base > a > ... > Link > a.

not sure if I'm doing something wrong..... or there's an issue?

**Comment by jxnblk** [comment]
React 15.2 introduced this warning. Rebass v0.3 should fix this, but instead of `Component` try the `is` prop, e.g. `<NavItem is={Link} />`

**Comment by keithn** [comment]
Thank you! that worked
