### ISSUE TITLE
Input on react v0.15.2

### ISSUE THREAD

**Issue by SimeonC** [jxnblk/rebass#99]
Hey on react v0.15.2 I'm getting the unknown prop `invalid` on input tag, I also get this for 'aria-invalid'.

`VM10648:44 Warning: Unknown prop `invalid` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

**Comment by jxnblk** [comment]
That's weird that aria-invalid is flagging the new warning. Are you still getting this with version 0.3?

**Comment by SimeonC** [comment]
I might be mistaken about aria-invalid, I think I tried ariaInvalid. But yes this is with v0.3. I'll check the aria invalid on Monday.

**Comment by SimeonC** [comment]
Ok, so aria-invalid doesn't throw an error, but it doesn't seem to do anything either - that might be my setup though.

**Comment by jxnblk** [comment]
You should be able to pass valid HTML attributes to components when needed, but Rebass should be stripping out custom props used in the library. If that's not the case feel free to reopen this issue with a link to a jsbin or similar.
